### ISSUE TITLE
README of PyPI package is broken and needs update

### ISSUE THREAD

**Issue by bittner** [SeleniumHQ/selenium#1137]
The Python implementation of the bindings for Selenium on PyPI has a README with at least two issues:

1. README **[is outdated](https://github.com/SeleniumHQ/selenium/blob/master/py/README)** (e.g. supported Python version 3.4 not mentioned but [declared on PyPI](https://pypi.python.org/pypi/selenium#downloads))
1. README **[doesn't display properly on PyPI](https://pypi.python.org/pypi/selenium)** (the source code displays instead of the formatted text)

The latter is probably related to a syntax error introduced in [commit 3fc2db2](https://github.com/SeleniumHQ/selenium/commit/3fc2db275149748b21ea0370d3d3ace2df7c2676#commitcomment-13704294) (table markup, line 17). It may also be advisable to use the currently missing `.rst` file extension.

**Comment by cgoldberg** [comment]
yikes... it looks like the PyPI page hasn't been rendering since the 2.45 release:

broken PyPI pages for last few releases:
* https://pypi.python.org/pypi/selenium/2.46.0
* https://pypi.python.org/pypi/selenium/2.46.1
* https://pypi.python.org/pypi/selenium/2.47.0
* https://pypi.python.org/pypi/selenium/2.48.0

I'm working on fixing these problems (and a few others I found).  I'll submit a PR shortly and link to it in this issue.

-Corey

**Comment by cgoldberg** [comment]
sumbitte.
see the PR cover letter and diff for details: https://github.com/SeleniumHQ/selenium/pull/1138

**Comment by barancev** [comment]
Fixed by commit 85741443926afdac0856c72b1fc099c0c448ebcb

**Comment by cgoldberg** [comment]
8574144 did not fix this issue.  It just renamed "README" to "README.rst".  That change alone just makes it render nicer when viewing through GitHub's website.  An additional change needs to be made in order to fix the issue of rendering on PyPI:

> README doesn't display properly on PyPI (the source code displays instead of the formatted text)

When a release gets published to PyPI, it is done using info declared in `setup.py`.  https://github.com/SeleniumHQ/selenium/blob/master/setup.py#L37 still has the following line:

`'long_description': open(join(abspath(dirname(__file__)), "py", "README")).read(),`

which should be updated to reflect the new renamed README:

`'long_description': open(join(abspath(dirname(__file__)), "py", "README.rst")).read(),`

---

I assume releasing to PyPI is currently broken without making this change. (because the README file it is referencing would not be found).

**Comment by cgoldberg** [comment]
@barancev can you re-open this issue?
thanks.

**Comment by barancev** [comment]
Fixed by commit 64b76a454e30bae274ddd0e006506d1009ac2ebe
