### ISSUE TITLE
[🐛 Bug]: Selenium Manger.exe does not find the config toml file

### ISSUE THREAD

**Issue by Kalste** [SeleniumHQ/selenium#12782]
### What happened?

I am running windows 10.
The selenium-manager.exe is in the folder "c:\LProg\Ldev\selenium_grid\grid4".
The config toml file is in the folder "C:\Users\myUser\.cache\selenium" and is named "se-config.toml".
The selenium manager is running fine with this command:
selenium-manager --proxy="myUser:myPassword@myProxy:myPort" --cache-path="C:\Users\myUser\.cache\selenium" --browser="firefox" --os="windows" --debug --trace

The geckodriver is downloaded.

But if I start the selenium-manager.exe without parameters, I am always getting the error message "ERROR   You need to specify a browser or driver".

But why, the config toml is in the folder "C:\Users\myUser\.cache\selenium".

This is my config toml file:

browser="firefox"
os="windows"
proxy="myUser:myPassword@myProxy:myPort"
cache-path="C:\Users\myUser\.cache\selenium"
debug=true
trace=true

### How can we reproduce the issue?

```shell
Create a config toml file with this content:

browser="firefox"
os="windows"
proxy="myUser:myPassword@myProxy:myPort"
cache-path="C:\Users\myUser\.cache\selenium"
debug=true
trace=true

Put the file in the folder "C:\Users\myUser\.cache\selenium" and start selenium-manager.exe
```

### Relevant log output

```shell
ERROR   You need to specify a browser or driver
```

### Operating System

Windows 10

### Selenium version

4.12.1

### What are the browser(s) and version(s) where you see this issue?

Firefox 102.14.0.8605

### What are the browser driver(s) and version(s) where you see this issue?

Geckodriver 0.33

### Are you using Selenium Grid?

Java 4.12.1

**Comment by bonigarcia** [comment]
Thanks a lot for reporting, @Kalste. Indeed, this is a bug in Selenium Manager. I'm working on the fix.

**Comment by bonigarcia** [comment]
I have just committed a patch to solve this. @Kalste Can you please try it? To do that, download the new Selenium Manager binary ([selenium-manager_windows-x32](https://github.com/SeleniumHQ/selenium/suites/16407571539/artifacts/937458676)) and use a shell to run this binary while your `se-config.toml` is in the cache:

```
selenium-manager
```
Please let me know the results; thanks.

**Comment by Kalste** [comment]
Hi @bonigarcia,
thanks for your fast answer and bugfix.
But I´m not sure if I made something wrong, because I still get the error.

What I did:
- Downloaded your ZIP-file and unpacked it
- The config toml file is in the folder, please see screenshot "folder.jpg"
- The content of the config toml file is this, please see screenshot "toml-file.jpg"
- Started selenium-manager.exe, please see the screenshot "start.jpg"
- Result: ERROR   You need to specify a browser or driver

What am I doing wrong?

![start](https://github.com/SeleniumHQ/selenium/assets/33020490/1b0784f5-edb7-4607-9505-94c43b497be0)
![folder](https://github.com/SeleniumHQ/selenium/assets/33020490/dd1a5616-e3bc-42fd-bc98-09feb29fab47)
![toml-file](https://github.com/SeleniumHQ/selenium/assets/33020490/b3c8208b-8d7b-48ec-9b84-03fdef10aea6)

**Comment by bonigarcia** [comment]
I think it is caused because of the entry `cache-path`. That one is special since the config file is read from the cache, and its handling is tricky. Please remove that entry from your toml file. I am going to review it in my side.

**Comment by bonigarcia** [comment]
Ah, I think I find it. Please use double backslash in your Windows path:

```
cache-path="C:\\Users\\xxxxx\\.cache\\selenium"
```

Nevertheless, I can try to make this more robust (to accept also single backslash)

**Comment by Kalste** [comment]
Yes, that are both the solutions.
Either deleting the entry "cache-path" or inserting double backslash.

If I use this: cache-path="C:\\Users\\myUser\\.cache\\test"

Is it possible that then I need 2 config toml files?
One in "C:\\Users\\myUser\\.cache\\selenium" and another in "C:\\Users\\myUser\\.cache\\test"

If not I get the known message: ERROR   You need to specify a browser or driver

**Comment by bonigarcia** [comment]
After digging into this issue, I concluded it is not a limitation in Selenium Manager. The use of the backslash in TOML must be escaped, or alternatively, use single quotes (see [reference](https://toml.io/en/v0.3.0)). In your case:

```
cache-path="C:\\Users\\xxxxx\\.cache\\selenium"
```

... or:

```
cache-path='C:\Users\xxxxx\.cache\selenium'
```

**Comment by bonigarcia** [comment]
This issue should be fixed in Selenium 4.13, recently released.
