### ISSUE TITLE
Can't click on WebElement

### ISSUE THREAD

**Issue by bmsantos** [SeleniumHQ/selenium#1533]
Selenium fails with the error below when trying to click on the WebElement.

The driver does click on the element when the Mac Book Pro screen resolution is set to its max: 1920 x 1200 but fails when using the Mac Book Pro default 1440 x 900 or 1680 x 1050 resolutions.

I can't avoid but wonder if this is related to [Mac Book Pro Retina scaled mode](http://www.anandtech.com/show/5996/how-the-retina-display-macbook-pro-handles-scaling).  

```
org.openqa.selenium.WebDriverException: Element is not clickable at point (1194.9000244140625, 611.2000122070312). Other element would receive the click: <footer class="footer"></footer>
Command duration or timeout: 68 milliseconds
Build info: version: '2.49.0', revision: '365eeb44deba2067b1761c8862ef21d55250e063', time: '2016-01-13 11:57:39'
System info: host: 'mbp.locall', ip: '192.168.5.7', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.11.2', java.version: '1.7.0_67'
Session ID: 99ed5a92-a255-f94c-8f2a-b1fe462d11c8
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities [{platform=MAC, acceptSslCerts=true, javascriptEnabled=true, cssSelectorsEnabled=true, databaseEnabled=true, browserName=firefox, handlesAlerts=true, nativeEvents=false, webStorageEnabled=true, rotatable=false, locationContextEnabled=true, applicationCacheEnabled=true, takesScreenshot=true, version=43.0.4}]
```

**Comment by barancev** [comment]
This issue should be fixed in 2.50.1
Feel free to reopen if it is still actual.

**Comment by bmsantos** [comment]
@barancev , sorry to inform that the issue is still occurring:

```
Time elapsed: 4.832 sec  <<< ERROR!
org.openqa.selenium.WebDriverException: Element is not clickable at point (1266.3499755859375, 647.4666748046875). Other element would receive the click: <footer class="footer"></footer>
Command duration or timeout: 59 milliseconds
Build info: version: '2.50.1', revision: 'd7fc91b29de65b790abb01f3ac5f7ea2191c88a7', time: '2016-01-29 11:11:26'
System info: host: 'Brunos-MBP', ip: '192.168.1.14', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.11.3', java.version: '1.8.0_66'
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities [{applicationCacheEnabled=true, rotatable=false, handlesAlerts=true, databaseEnabled=true, version=44.0, platform=MAC, nativeEvents=false, acceptSslCerts=true, webStorageEnabled=true, locationContextEnabled=true, browserName=firefox, takesScreenshot=true, javascriptEnabled=true, cssSelectorsEnabled=true}]
Session ID: 750ebbe1-7081-2741-8569-908ca87dfeb6
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:206)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:158)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:678)
	at org.openqa.selenium.remote.RemoteWebElement.execute(RemoteWebElement.java:327)
	at org.openqa.selenium.remote.RemoteWebElement.click(RemoteWebElement.java:85)
        ...
```

**Comment by barancev** [comment]
For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)

**Comment by bmsantos** [comment]
Yes yes!! I get it!

Will get back to you with a sample. Can't use the one where that is happening!

You testing guys! :)

**Comment by shabana-parveen** [comment]
selenium latest version 3.5.2 throwing NullPointerExpection for all WebElements.
I try to resolve this issue in my whole day, then I just downgrade the selenium version with 3.4.0, Now its working. Could you please guide me why the selenium latest version is not supporting the WebElements with the appium?

I tried all elements with click(), clear(), sendkeys() and getText(), getAttribute() etc.

Please refer below exception log:
java.lang.NullPointerException at org.openqa.selenium.remote.RemoteWebElement.execute(RemoteWebElement.java:275) at org.openqa.selenium.remote.RemoteWebElement.clear(RemoteWebElement.java:117)
