### ISSUE TITLE
IEDriver blowing up on child windows containing only a PDF...

### ISSUE THREAD

**Issue by DamienLyles** [SeleniumHQ/selenium#1624]
Hello,

I'm using Ruby (without Rails) selenium-webdriver gem 2.51.0.  In one of our tests, we click a link that spawns a child window that only contains a PDF.  Our code is blowing up when we try to get the current url for that window (i.e., driver.current_url).  The code works when we use version 2.48 of the IEDriver executable, but not when we use 2.49 - 2.51.

The error that we're getting is 'No connection could be made because the target machine actively refused it. - connect(2) for "127.0.0.1" port 5555.'

The code that we use to declare our driver follows:

caps = Selenium::WebDriver::Remote::Capabilities.ie
caps['ignoreProtectedModeSettings'] = true
caps['ignoreZoomSetting'] = true  
caps['javascriptEnabled'] = true
caps['acceptSslCerts'] = true  
caps['nativeEvents'] = true 
caps['takesScreenshot'] = true
caps['handlesAlerts'] = true
caps['requireWindowFocus']= true
# caps['proxy']= ieproxy

localdriver = Selenium::WebDriver.for :ie, :desired_capabilities => caps

My IE uses a proxy if that matters...

The link on my test page that launches the child window is...
&lt;a href="javascript:openWIN('WFServlet.pdf','yes',false);" id="basic_pdf_id"&gt;Basic PDF&lt;/a&gt;

my 'openWIN' function basically boils down to...
window.open(url,'','width=1000,height=600,scrollbars='+scrollbar_setting+',resizable=no,status=yes');

**Comment by DamienLyles** [comment]
It has been a few months.  Shouldn't this be assigned to the maintainers of the IEDriver by now?

**Comment by jimevans** [comment]
Given that "the maintainers of the IEDriver" consists entirely of a single volunteer, who does not devote more than a small amount of his time to the driver, I'm not sure what prioritization you're expecting.

**Comment by DamienLyles** [comment]
I appreciate all of the work that you guys have done in creating and, now, maintaining Selenium WebDriver. I'm sure that it can be quite time consuming!  The fact that you guys do this free of charge when you are not required to do so is not lost on me.  

My concern is that my team is stuck using version 2.48 of IEDriverServer because PDFs are a big part of what we do.  I also wasn't sure if anyone was working on this problem because this issue currently has a status of "No one assigned".

Thank you for the quick reply!
Damien L

**Comment by jimevans** [comment]
This should be fixed in f0c7418

**Comment by DamienLyles** [comment]
Hello,
What version of IEDriverServer should we be looking for this to work in?  I tried the new 3.0, but I'm still seeing the timeout issue.

**Comment by DamienLyles** [comment]
Nevermind.  Confirmed fix in version 3.3.0.0
