### ISSUE TITLE
[🐛 Bug]: Edge fails with Selenium Manager "Unable to obtain browser driver"

### ISSUE THREAD

**Issue by mantheypw** [SeleniumHQ/selenium#16335]
### Description

Trying to run Selenium with Edge using Selenium Manager.
Works with Chrome but fails on Microsoft Edge and when I have the version set to 140.
So its failing on downloading version 139.

On checking the logs, I think its trying to download the driver from the wrong location. It should be:
https://msedgedriver.microsoft.com/139.0.3405.125/edgedriver_win64.zip

### Reproducible Code

```shell
driver = await new Builder()
            .forBrowser('MicrosoftEdge')
            .withCapabilities({
                browserName: 'MicrosoftEdge',
            browserVersion: '139' // replace with your desired version
            })
            .build();
```

### Debugging Logs

```logs
Error: Unable to obtain browser driver.
        For more information on how to install drivers see
        https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location/. Error: Error executing command for C:\Users\______\VS_Code\selenium-automation\node_modules\selenium-webdriver\bin\windows\selenium-manager.exe with --browser,MicrosoftEdge,--language-binding,javascript,--output,json,--browser-version,139: MicrosoftEdge 139 cannot be downloaded
```

**Comment by diemol** [comment]
The download location was changed, and this was fixed in 4.35. Please upgrade.

**Comment by mantheypw** [comment]
Hi Diemol,
Thank you for looking into this.
I can see this as fixed but I am still getting this error in the latest version for Selenium in Javascript (4.35.0).

I am trying to use Selenium Manager to download older versions of Edge. So for example for v139.0.3405.125, it should pick-up the driver from:
[139.0.3405.125](https://msedgedriver.microsoft.com/139.0.3405.125/edgedriver_win64.zip)

Can I confirm where the driver is downloaded from currently?

**Comment by diemol** [comment]
https://github.com/SeleniumHQ/selenium/blob/569934ab66e9eecb0ec1c3c3d152434202febbc3/rust/src/edge.rs#L48

**Comment by cgoldberg** [comment]
Selenium Manager should be able to download EdgeDriver for older versions (like 139) fine. However, the issue is that it can't find a matching version of Edge browser to download. Microsoft pulls older versions from the download site that Selenium Manager uses. For example, currently they only have Edge 140-142 available for most platforms:

https://edgeupdates.microsoft.com/api/products/

I'm not sure we can do anything about this besides possibly give a better error message that the browser is not available.

@mantheypw specifying version 140 or letting it grab the latest version should fix your issue.
