### ISSUE TITLE
[🐛 Bug]: WebElement.click() does not properly scroll element into view (scroll "jerks" a few pixels but fails to make element clickable)

### ISSUE THREAD

**Issue by USSQA** [SeleniumHQ/selenium#16345]
**What I was trying to do:**
Click an off-screen element on a public webpage using WebElement.click().

**Expectation**
Per the [click specification](https://w3c.github.io/webdriver/#element-click), `.click()` should automatically scroll the element fully into view so it can be interacted with.

**Observed Behavior:**
Instead of fully scrolling the element into view, the browser scrolls only a few pixels (appearing to "jerk" a few times) and then stops. The element remains obscured and out of the view, and the click fails with an `ElementClickInterceptedException`.

**Downstream reports:** 
Selenide [#2850](https://github.com/selenide/selenide/issues/2850), [#2882](https://github.com/selenide/selenide/issues/2882)

**Relevant context / configuration:**
- Reproduced on Windows 11 and Alpine Linux 3.22
- Selenium 4.35.0 (Java bindings)
- Google Chrome Version 140.0.7339.128 (Official Build) (64-bit)
- Chromium Version 140.0.7339.185-r0 (Official Build) (64-bit)
- Chromedriver auto-managed
- Behavior is the same in headless and headed mode
- Increasing viewport size (e.g., 1920x1080) does not avoid the bug

**Error message:**
`org.openqa.selenium.ElementClickInterceptedException: element click intercepted: Element is not clickable at point (362, 1663)`

**Demonstration:**
![Image](https://github.com/user-attachments/assets/9ce6a002-6421-46d3-8a78-6353413c70be)

### Reproducible Code

```shell
import org.junit.jupiter.api.RepeatedTest;
import org.openqa.selenium.By;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;

public class DemoScrollBug {

    @RepeatedTest(10)
    void demo() {
        WebDriver driver = new ChromeDriver();
        try {
            driver.manage().window().setSize(new Dimension(1920, 1080));
            driver.navigate().to("https://www.microsoft.com/en-us/microsoft-365/online-surveys-polls-quizzes");
            driver.findElement(By.xpath("//button[span[contains(text(), 'Organize your life')]]")).click();
        } finally {
            driver.quit();
        }
    }

}
```

### Debugging Logs

```logs
org.openqa.selenium.ElementClickInterceptedException: 
element click intercepted: Element is not clickable at point (370, 1675)
  (Session info: chrome=139.0.7258.154)
Build info: version: '4.35.0', revision: '1c58e5028b'
System info: os.name: 'Linux', os.arch: 'amd64', os.version: '5.14.0-570.32.1.el9_6.x86_64', java.version: '21.0.8'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Command: [2ce61b925c8510c202a75b112c59ab8f, clickElement {id=f.64897B940898240B98A1C5FF2907869D.d.8A7487F6B30E9933667D7146120809E1.e.51}]
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 139.0.7258.154, chrome: {chromedriverVersion: 139.0.7258.154 (9e0d6b2b47f..., userDataDir: /tmp/.org.chromium.Chromium...}, fedcm:accounts: true, goog:chromeOptions: {debuggerAddress: localhost:45675}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: linux, proxy: Proxy(), se:cdp: ws://localhost:45675/devtoo..., se:cdpVersion: 139.0.7258.154, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:extension:minPinLength: true, webauthn:extension:prf: true, webauthn:virtualAuthenticators: true}
Element: [[ChromeDriver: chrome on linux (2ce61b925c8510c202a75b112c59ab8f)] -> xpath: //button[span[contains(text(), 'Organize your life')]]]
Session ID: 2ce61b925c8510c202a75b112c59ab8f
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486)
	at org.openqa.selenium.remote.ErrorCodec.decode(ErrorCodec.java:167)
	at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:138)
	at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:50)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:215)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.invokeExecute(DriverCommandExecutor.java:216)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:174)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:557)
	at org.openqa.selenium.remote.RemoteWebElement.execute(RemoteWebElement.java:223)
	at org.openqa.selenium.remote.RemoteWebElement.click(RemoteWebElement.java:76)
	at DemoScrollBug.demo(DemoScrollBug.java:15)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at java.base/java.util.Optional.ifPresent(Optional.java:178)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.stream.IntPipeline$1$1.accept(IntPipeline.java:180)
	at java.base/java.util.stream.Streams$RangeIntSpliterator.forEachRemaining(Streams.java:104)
	at java.base/java.util.Spliterator$OfInt.forEachRemaining(Spliterator.java:712)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
```

**Comment by cgoldberg** [comment]
I just investigated this, and I think the issue is with Chrome's smooth scroll behavior.

Here is a script that reproduces the issue in Python:

```python
import logging

from selenium import webdriver
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.common.by import By
from selenium.webdriver.support import expected_conditions as EC

logging.basicConfig(level=logging.DEBUG)

driver = webdriver.Chrome()
driver.get("https://www.microsoft.com/en-us/microsoft-365/online-surveys-polls-quizzes")
elem = WebDriverWait(driver, 5).until(EC.visibility_of_element_located((By.XPATH, "//button[span[contains(text(), 'Organize your life')]]")))
print(elem.location)
elem.click()
```

It waits for the element to be visible, and attempts to click it. This will crash with `selenium.common.exceptions.ElementClickInterceptedException: Message: element click intercepted`
... even though the element is visible and displayed.

Looking at the debug logs, you can see chromedriver says the element's location is `(56, 1544)`:
```
DEBUG:selenium.webdriver.remote.remote_connection:GET http://localhost:49607/session/d74f627c8c3d1fa886b9e96f99f7496c/element/f.2B87A5B4A85456F11F2D12543D474A4F.d.820D3AF23F67DBA9B3DB67BB115C8347.e.25/rect {}
DEBUG:selenium.webdriver.remote.remote_connection:Remote response: status=200 | data={"value":{"height":40,"width":164,"x":56,"y":1543.800048828125}} | headers=HTTPHeaderDict({'Content-Length': '64', 'Content-Type': 'application/json; charset=utf-8', 'cache-control': 'no-cache'})
```

However, when you try to click it, it sends the click to a different location `(137, 1563)`:
```
DEBUG:selenium.webdriver.remote.remote_connection:POST http://localhost:49607/session/d74f627c8c3d1fa886b9e96f99f7496c/element/f.2B87A5B4A85456F11F2D12543D474A4F.d.820D3AF23F67DBA9B3DB67BB115C8347.e.25/click {}
DEBUG:selenium.webdriver.remote.remote_connection:Remote response: status=400 | data={"value":{"error":"element click intercepted","message":"element click intercepted: Element is not clickable at point (137, 1563)
```

Oddly, you can click the button fine using JavaScript:
```
driver.execute_script("arguments[0].click();", elem)
```

but chromedriver can't find it.

If you disable smooth scrolling when starting Chrome, everything works fine... the element is scrolled into view and can be clicked:
```
options = webdriver.ChromeOptions()
options.add_argument("--disable-smooth-scrolling")
driver = webdriver.Chrome(options=options)
```

Since we are sending the correct request to chromedriver, I don't think this is a Selenium issue or fixable on our side. It would have to be addressed by the Chromium team.

Also note, I reproduced the same issue in Firefox, but didn't try any workarounds.

**Comment by cgoldberg** [comment]
@Idris-elaboration that is not in any way helpful

**Comment by krishnaharshap** [comment]
@cgoldberg I've encountered a similar issue where WebElement.click() fails to scroll the element fully into view, leading to an ElementClickInterceptedException. I've observed this behavior across different operating systems and browsers. To assist in diagnosing the issue, I can provide detailed logs and screenshots. Additionally, I can test the issue with various versions of Selenium and Chromedriver to identify any version-specific problems. Please let me know nxt steps and happy happy to help!
Thanks,
Krishna

**Comment by cgoldberg** [comment]
@krishnaharshap as I explained in my comment, I've seen the logs when this occurs, and Selenium is sending the correct request to chromedriver, so it's not a selenium issue and isn't dependant on a specific version or language binding. If you want to diagnose which versions of chromedriver it occurs with, go ahead, but that information would be useful to the Chromium developers, not us.

**Comment by krishnaharshap** [comment]
Hi @cgoldberg, thanks for clarifying that this behavior lies out of scope for Selenium, and likely Chromium issue.

To support the community (and possibly upstream Chromium), I’d like to gather a detailed version-matrix: Chrome versions + ChromeDriver versions + Selenium versions, reproduce this sample case, take logs/screenshots showing the scroll “jerk” + click failure behavior, and see if we can spot any pattern or workaround. May I proceed with that investigation?

If you’d prefer I focus only on a workaround (e.g., JS scrollIntoView + explicit waits) instead, I’m happy to do so.

Thanks alot!
Krishna

**Comment by mwdle** [comment]
@krishnaharshap This issue is beyond me, but to reiterate some of the information that has already been provided, the issue is not limited to just Chrome. It has been confirmed to occur in Firefox as well, for what it's worth.

As @cgoldberg described, a workaround already exists, and that is disabling smooth scrolling in the browser you are automating:
> If you disable smooth scrolling when starting Chrome, everything works fine... the element is scrolled into view and can be clicked:
> 
> ```
> options = webdriver.ChromeOptions()
> options.add_argument("--disable-smooth-scrolling")
> driver = webdriver.Chrome(options=options)
> ```


Additionally, use a JS scroll into view or JS click is also a functional workaround.

It may be helpful for you to review the downstream reports of this issue as well:

> **Downstream reports:**
> Selenide [#2850](https://github.com/selenide/selenide/issues/2850), [#2882](https://github.com/selenide/selenide/issues/2882)

Hope that helps

**Comment by cgoldberg** [comment]
> May I proceed with that investigation?

You can investigate anything you want... but whatever you find isn't going to be useful for us. However, feel free to report it to the browser maintainers if they are interested.

**Comment by krishnaharshap** [comment]
Thanks @cgoldberg , @mwdle for the valuable inputs. I'll refer to selenide issue reports to identify if any further investigation needed. Appreciate your time!

**Comment by ShubhamAgarwalGit** [comment]
I am facing same issue , is it solved by chromium team ? does any one has any insight or some resource link related to it ?
 @cgoldberg , @mwdle

**Comment by cgoldberg** [comment]
@ShubhamAgarwalGit no, it is not solved. Disable smooth scrolling to work around it.

**Comment by titusfortner** [comment]
@mwdle do you have logs for the Firefox failure? Selenium isn't doing anything different, but as browsers are updating their implementations to use the new specifications we expect there to be some issues on their end. I'll add links to where to file the chrome bug and if we also see it in Firefox we can add that as well.

Thanks for raising and contributing to this issue.

**Comment by mwdle** [comment]
@titusfortner Unfortunately, I don't have any Firefox logs for this. I haven't tested it in Firefox myself, I was just reiterating what user cgoldberg and the downstream Selenide reports mentioned.

I don't intend to file this issue with the chromedriver or firefox teams (downstream reports even indicated that [safari may be affected?](https://github.com/selenide/selenide/issues/2850#issuecomment-3327437946)). The `--disable-smooth-scrolling` workaround works for my team, so I don't have a vested interest in pushing this issue forward.

Happy for someone else to take the lead on that if anyone is willing. Thanks for looking into it
