### ISSUE TITLE
Select Method with selectby index is not working for the Selenium 3.0.0-beta3

### ISSUE THREAD

**Issue by pardeepkmail** [SeleniumHQ/selenium#2799]
## Meta -
OS:   Windows 7 
Selenium Version: 3.0.0-beta3, Eclipse Neon
Browser:   Firefox48 with GECKODRIVER

Browser Version:  48.0.2

## Steps to reproduce -
![selenium select issue](https://cloud.githubusercontent.com/assets/22299372/18665156/7ea75a98-7f43-11e6-9685-128e55aadbed.png)

**Comment by pardeepkmail** [comment]
I am not sure whether it is issue or not but I am facing this problem in selecting the drop-down value after upgraded to Selenium  3.0.0-beta3 from 2.53.1 in old version same script was running perfectly. Also attached the screenshot for the error.

**Comment by jbonica** [comment]
I have experienced issues with trying to use the Select class with firefox 48.02 and Selenium 3.0.0-beta3. The page in question has a few textfields in a questionnaire and then a pulldown. In the automated test, I can see the textfields being filled in and then when coming to the pulldown, I see the textfields are cleared, which shouldn't happen as there is no element on the page to reset these fields. The test just hangs without throwing an exception.

**Comment by patthiel** [comment]
I am encountering the same issue on selenium beta 3 in Safari 10.

**Comment by Easyman123** [comment]
I have the same problem using Selenium 3.0.0-beta3 with geckodriver v0.10.0 and firefox browser version 49.0
Selectby Value and selectby visibleText are working fine instead.

**Comment by AutomatedTester** [comment]
A lot of the select issues in Firefox have been fixed in Firefox 49. If they are not working still, please reopen and please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)

**Comment by bethiel1** [comment]
This is occurring for me today using selenium-java 3.0.1 in Firefox 50.

**Comment by vaishnavidesai** [comment]
I am still facing the issue on Safari 10 browser with selenium 3.3.1 and am unable to select the value in drop down with selectbyindex or any other methods. Help please.

**Comment by patthiel** [comment]
@vaishnavidesai we encountered the same months ago and it has totally blocked us from doing safaridriver automation. Not sure if this is a problem on the selenium side or driver implementation side. I filed an issue on the apple developer forum https://forums.developer.apple.com/message/184592#184592 but have never got a response only other idea i have is bugging an apple dev about it 😉  cc. @burg

I can provide a reproduceable repo/spec if needed.

**Comment by vaishnavidesai** [comment]
Thanks for following up. If you find a solution for it or apple gets back please provide details here!
Thanks again.

**Comment by svetikshark** [comment]
Having the same issue - not able to select from dropdown on safari . Has anyone any ideas how to fix or overcome this problem?

**Comment by svetikshark** [comment]
overcoming now with javascript 
 element.ExecuteScript("document.getElementById('" + element.Id + "').value = " + optionName);

**Comment by burg** [comment]
@svetikshark: the Select class in Java uses clicking on the <option> element under the hood. We just released Safari Technology Preview 41 with a fix for this particular issue: https://webkit.org/blog/7989/release-notes-for-safari-technology-preview-41/

Please try it with STP 41's safaridriver and let me know if it still doesn't work.

-Brian

**Comment by ramiraj917** [comment]
Having the same issue - not able to select from dropdown on Firefox.
