### ISSUE TITLE
Firefox profiles with RemoteWebDriver

### ISSUE THREAD

**Issue by martmo** [SeleniumHQ/selenium#3046]
## Meta -
OS:  
Windows Server 2-12 R2

Selenium Version:  
3.0.1

Browser:  
Firefox 47.0.1 

Browser Version:  
47.0.1

## Expected Behavior -
When running tests from .Net client all is well, tests run as expected.  Once tests are completed, the firefox profiles generated on the target Grid nodes in temp directories should be deleted.

## Actual Behavior -
The firefox profiles generated in C:\users\<username>\AppData\Local\Temp\ with name anonymous<Guid>webdriver-profile are not deleted once the tests complete.  Each one of these dir are ~4 MB which very quickly adds up to considerable space.  When running under 2.53.1 this did not occur, is this a reoccurrence of an earlier bug?

**Comment by lukeis** [comment]
this should have been fixed in 3.0.1 related issue #2914

**Comment by martmo** [comment]
Definitely still an issue, our C# code is identical to that we were running on Selenium 2.53.1 plus we are calling RemoteWebDriver.Quit() to initiate cleanup

**Comment by bradhasha** [comment]
@lukeis This is still an issue for me as well.  My temp directory on my selenium grid server is becoming full fairly quickly.  I am calling driver.quit(), but the temporary profiles do not get deleted.

**Comment by mart44** [comment]
@bradhasha in the end we reverted back to 2.53.1 as we were unable to resolve the issue with profiles not being cleaned up

**Comment by bradhasha** [comment]
Thank you @mart44.  I'll probably do the same until this issue is resolved.

**Comment by matthiasstock** [comment]
As a workaround, you can delete old profiles by a cron or similar scheduled task until this issue is fixed (occurs on CentOS 6.8 also).

```
find /tmp/*webdriver-profile -maxdepth 0 -type d -mmin +60 -exec rm -rf "{}" \;
```

**Comment by diemol** [comment]
Duplicate of #5209

(and fixed via https://github.com/SeleniumHQ/selenium/commit/0bea0a1a09accff51cf197c8ac190242a4075348)
