### ISSUE TITLE
_cookie_temp_file being closed and removed twice

### ISSUE THREAD

**Issue by francisbergin** [SeleniumHQ/selenium#3216]
## Meta -
OS: Windows 7 (Cygwin)
Selenium Version: 3.0.2
Browser: PhantomJS
Browser Version: 2.1.1
Language: Python
Language Version: 3.4.5

## Expected Behavior -
When quitting the driver with `WebDriver.quit()`, `Service.send_remote_shutdown_command()` which closes and removes `_cookie_temp_file` should be called only once.

## Actual Behavior -
Whenever the Python GC runs and executes `Service.__del__()`, `Service.send_remote_shutdown_command()` is called again and attempts to close and delete `_cookie_temp_file` a second time causing a `FileNotFoundError` and an `OSError: [Errno 9] Bad file descriptor`.
## Steps to reproduce -
```python
import gc
from selenium import webdriver
driver=webdriver.PhantomJS()
driver.get('https://google.com')
driver.quit()
driver=1
gc.collect()
```

## More info -
The problem seems to occur when the PhantomJS process is not terminated and the garbage collector runs. There is often a delay between sending the `quit` command to PhantomJS and the process actually ending and if the garbage collector happens to run during that time and `self.process` is [not `none`](https://github.com/SeleniumHQ/selenium/blob/cdebe0e55f8dfaa2294f18f73aeb513fa76e0aef/py/selenium/webdriver/common/service.py#L145), then `send_remote_shutdown_command()` is run a second time. Also, this issue will most likely happen to users experiencing #767.

**Comment by cgoldberg** [comment]
#3263 should fix this

**Comment by fbergin** [comment]
This seems to be fixed. Tested in version `3.3.1`.

**Comment by jmbowman** [comment]
I'm still seeing this same problem with 3.3.1 on Python 2.7, Mac OS X 10.11.6, as well as Python 2.7 and 3.2 on Travis (Ubuntu 12.04.5):

```
Traceback (most recent call last):
  File "/Users/jeremybowman/Source/needle/.tox/py27/lib/python2.7/site-packages/nose/suite.py", line 228, in run
    self.tearDown()
  File "/Users/jeremybowman/Source/needle/.tox/py27/lib/python2.7/site-packages/nose/suite.py", line 351, in tearDown
    self.teardownContext(ancestor)
  File "/Users/jeremybowman/Source/needle/.tox/py27/lib/python2.7/site-packages/nose/suite.py", line 367, in teardownContext
    try_run(context, names)
  File "/Users/jeremybowman/Source/needle/.tox/py27/lib/python2.7/site-packages/nose/util.py", line 471, in try_run
    return func()
  File "/Users/jeremybowman/Source/needle/needle/cases.py", line 83, in tearDownClass
    cls.driver.quit()
  File "/Users/jeremybowman/Source/needle/.tox/py27/lib/python2.7/site-packages/selenium/webdriver/phantomjs/webdriver.py", line 76, in quit
    self.service.stop()
  File "/Users/jeremybowman/Source/needle/.tox/py27/lib/python2.7/site-packages/selenium/webdriver/common/service.py", line 149, in stop
    self.send_remote_shutdown_command()
  File "/Users/jeremybowman/Source/needle/.tox/py27/lib/python2.7/site-packages/selenium/webdriver/phantomjs/service.py", line 67, in send_remote_shutdown_command
    os.close(self._cookie_temp_file_handle)
OSError: [Errno 9] Bad file descriptor
```

Maybe the code should be more defensive, setting `self._cookie_temp_file` to `None` immediately after removing it so it won't attempt to do so again?

**Comment by dm-wyncode** [comment]
I was doing some experimentation with Python's contextlib and ran into this issue.

When main in this gist is run, this issue happens approximately 3 times in 10: https://gist.github.com/dm-wyncode/56ad352aa0a22532c34b9426b4b688bd#file-performance-py

environment info:
Linux 4.9.7-x86_64-linode80 x86_64 x86_64 x86_64 GNU/Linux
python 3.4
phantomjs version 2.1.1
selenium==3.3.3

**Comment by pxpeterxu** [comment]
I'm also getting this error with the following code:

```python
import gc
from selenium import webdriver

driver = webdriver.PhantomJS()
url = 'https://www.google.com'
driver.get(url)

print 'Quitting'.format(i)
driver.quit()

driver = webdriver.PhantomJS()
driver.get(url)

gc.collect()
driver.quit()  # Error happens here
```

### Expected behavior
Successful execution

### Actual behavior
```
OSError: [Errno 9] Bad file descriptor
  File "temp.py", line 15, in <module>
    driver.quit()  # Error happens here
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/phantomjs/webdriver.py", line 76, in quit
    self.service.stop()
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/common/service.py", line 149, in stop
    self.send_remote_shutdown_command()
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/phantomjs/service.py", line 67, in send_remote_shutdown_command
    os.close(self._cookie_temp_file_handle)
OSError: [Errno 9] Bad file descriptor
```

**Environment info:**
Ubuntu 16.04.2 LTS
Python 2.7.12 (from distribution package)
phantomjs version 2.1.1 (from distribution package)
selenium == 3.4.1

It seems like what's going on is that:
1. We call .quit(): the cookie file's descriptor gets closed
2. We create a new driver. The new cookie file descriptor happens to be the same number as the now-closed file descriptor
3. We garbage collect the original driver. The *new* cookie file descriptor gets deleted
4. When we try to call quit() again, it errors because the file descriptor has been closed

I think @jmbowman's suggestion that we make the code more defensive by nulling the file descriptor after https://github.com/SeleniumHQ/selenium/blob/master/py/selenium/webdriver/phantomjs/service.py#L67 is the way to go here.

**Comment by lovew** [comment]
agree with @pxpeterxu

**Comment by brn7331** [comment]
Confirmed on 
Ubuntu 14.04.5 LTS
Python 3.4.3

as a workaround I use a fixed cookie path with phantomjs (--cookies-file=/cookies.txt)

**Comment by blazerpraveen** [comment]
@brn7331 can you explain in detail pls??

**Comment by lmtierney** [comment]
Closing this as PhantomJS is being deprecated in favor of headless Chrome or Firefox
