### ISSUE TITLE
driver = webdriver.Firefox() complains about: Your Firefox profile cannot be loaded. It may be missing or inaccessible.

### ISSUE THREAD

**Issue by aaltat** [SeleniumHQ/selenium#3743]
## Meta -
OS:  
Windows 10

Selenium Version:  
3.3.1

Browser:  
Firefox

Browser Version:  
52.0.1 (32-bit)

## Expected Behavior -
When running this `driver = webdriver.Firefox()` Firefox would open successfully. 
Then the Python script would run without errors. 
## Actual Behavior -
There is dialog with the Firefox which states the following: ```Your Firefox profile cannot be loaded. It may be missing or inaccessible.``` The Python method does not continue until the dialog is accepted manually. 

## Steps to reproduce -
```
from selenium import webdriver
from selenium.webdriver.common.keys import Keys

driver = webdriver.Firefox()
driver.get("http://www.python.org")
assert "Python" in driver.title
elem = driver.find_element_by_name("q")
elem.clear()
elem.send_keys("pycon")
elem.send_keys(Keys.RETURN)
assert "No results found." not in driver.page_source
driver.close()
driver.quit()
```

**Comment by aaltat** [comment]
With resent Selenium and geckodriver version this is fixed. Closing.

**Comment by saitam1** [comment]
This is still an issue with:
Mozilla Firefox Snap for Ubuntu canonical-002 - 1.0 - 67.0.4 (64-bit) 
Selenium 3.141.0
