### ISSUE TITLE
Alert handling fails in latest IE version

### ISSUE THREAD

**Issue by abhinavm88** [SeleniumHQ/selenium#3791]
## Meta -
OS:  
Windows 10 Enterprise
Selenium Version:  
3.3.1
Browser:  
Internet Explorer

Browser Version:  
11.953.14393.0

## Expected Behavior -
I was running the same test script for last 3 months. Suddenly last week it started failing in verifying the alert text. One difference I could find is now if the same alert is displayed within a short time span there is a warning with checkbox. Warning message is "don't let this page create more messages".  

Alert alert = driver.switchTo().alert();
alertText = alert.getText();
alert.getText() should return the text.

## Actual Behavior -
It is not returning the alert text.

## Steps to reproduce -
Use the same version of IE 11 as mentioned, generate some browser native alert within a short span(say 2 sec).

**Comment by vgm106** [comment]
I am able to replicate the same issue with watir

OS: Win 7 Enterprise 64bit
IE 11.0.9600.18617
ruby 2.3.3p222 (2016-11-21 revision 56859) [x64-mingw32]
watir 6.2.0
IEDriverServer 3.3.0 32bit

**Comment by aneeshchandy** [comment]
What you are seeing is a browser feature. Try adding some "pause" to slow down the alert generation frequency in a certain time.

Are you supposed to see so many alerts in a short time frequency like this? Maybe the app under test should use custom JS/JQuery pop-ups than to use window.alert.

**Comment by jimevans** [comment]
I'm entirely unable to reproduce this behavior in current versions of IE. I'm using 11.0.15063.0 and am unable to generate a page that displays an alert with the checkbox. Can you provide a sample page that does so?

**Comment by abhinavm88** [comment]
@aneeshchandy  We have completed 700+ test scripts and there are many instances like this. So it will be very difficult to slow down using some waits. Changing in application is impossible for us :( . Any method to disable this feature in IE is highly appreciated. Thanks.

**Comment by abhinavm88** [comment]
@jimevans  : I think with the version you mentioned its not reproducible. I am not able to reproduce with another version of IE 11(11.0.9600.18538).  Unfortunately I can not make any site with this alert.

**Comment by vgm106** [comment]
@abhinavm88 Apologies, my issue was sightly different and probably related to watir + IE web driver. Any attempt at calling alert methods would close it including something like browser.alert.ok or .text instead of clicking ok on the alert box or getting its text. I updated to watir 6.2.1 and it was a not  an issue anymore.

**Comment by aneeshchandy** [comment]
@abhinavm88 Just to make things clearer, let me ask these questions:
* You were earlier seeing a specific kind of alert, and now you are seeing this new alert (which is not what you expected to see)?
* Are you able to read the alert text from this new alert?

Turn off browser feature is not recommended (and sometimes impossible)

**Comment by abhinavm88** [comment]
@aneeshchandy 
You were earlier seeing a specific kind of alert, and now you are seeing this new alert (which is not what you expected to see)? - Yes. Now a checkbox with text 'don't let this page create more messages' is displayed.

Are you able to read the alert text from this new alert? - I can read it with eyes not with selenium webdriver. But I am able to accept or dismiss the alert using selenium.

**Comment by abhinavm88** [comment]
@jimevans You can try the 'Confirm pop up' button in http://toolsqa.com/handling-alerts-using-selenium-webdriver/

Try clicking this button twice immediately.

**Comment by abhinavm88** [comment]
Another point is that in chrome "Prevent this page from creating additional dialogs" is displayed but alert.getText() will return the correct text without any issue. So I feel this should be fixed from IEDriver or selenium.

**Comment by jimevans** [comment]
@abhinavm88 I don't dispute this is a legitimate issue, but I can't reproduce it with the version of IE I'm currently working with. Until and unless I can get a virtual machine that has the appropriate checkbox on an alert in IE, there's nothing I can do about it. I'll need to ask for your patience until I can get an environment where I can see and work with the alert type you describe.

**Comment by abhinavm88** [comment]
Any update on this issue?

**Comment by abhinavm88** [comment]
I tried with the latest IE Driver version. No luck :(  IEDriverServer 3.4

**Comment by naiad09** [comment]
Fill the same, IE driver hangs on alert switcihng

**Comment by jimevans** [comment]
I believe this has been fixed with changes to the alert dialog detection code that landed in 3.5.x.

**Comment by BathiyaL** [comment]
I'm using InternetExplorerDriver 3.6.0.0 and I'm still facing this issue: unfortunately we cannot disable this from browser end.
