### ISSUE TITLE
selenium-webdriver (2.45) running test very slow

### ISSUE THREAD

**Issue by tarar1** [SeleniumHQ/selenium#383]
Today i have upgraded selenium-webdriver from 2.43 to 2.45 its really slows down the test execution.
the test use to run in 3 min 20 seconds now taking 5 minutes to run.
after switching to the old driver again test run time went back to original.

**Comment by lukeis** [comment]
you don't mention which browser (and versions) you're running with nor which platform(s). Also one would hope you would provide some sample scripts of sorts to help us understand the issue.

I happen to know there was a performance issue with FirefoxDriver in the latest release that has been fixed since, but we need to do another release for.

Closing this issue since it's not actionable.

**Comment by phoenix384** [comment]
probably the same: https://code.google.com/p/selenium/issues/detail?id=8551
Why isn't that fix released?

**Comment by benkiefer** [comment]
@lukeis Can we get this released? There has been a lot of chatter on the thread that @phoenix384 mentioned.

**Comment by andreastt** [comment]
That patch hasn't been vetted against different Firefox versions.  If someone can do that, we're happy to include it.

**Comment by benkiefer** [comment]
Should this issue be left open then?

**Comment by andreastt** [comment]
Sorry, my earlier comment was wrong.  The fix has landed on master, but we're currently experiencing infrastructure problems with our CI that are preventing us from releasing a new version with this fix in it.

Sorry for the inconvenience this is causing, but hopefully we'll have that resolved soon (-:

In the meantime it's possible to build Selenium from source by doing `./go clean release`.

**Comment by rcgeorge23** [comment]
Any update on when this fix will be released?

**Comment by duncan-bayne** [comment]
@andreastt are you still having CI troubles?  Is it the sort of thing that could be addressed by the community?  I'm keen to help expedite a release of this :smile:

**Comment by titusfortner** [comment]
I saw the infrastructure issues were fixed a couple weeks ago, but here is the current, less than happy status - http://ci.seleniumhq.org:8080/

**Comment by renuc** [comment]
I am still seeing issues with our CI builds some jobs that used to run for 2 hours run for 16!! Can we have this issue re-opened till we have a release ready to fix?

**Comment by rbu** [comment]
Firefox 38 was pushed to CentOS 6 today, which means there's going to be a significant chunk of users who can't use the old gem anymore and will have to use latest release which includes this bug.

Could you please consider the 10 comments on this issue, the 75 comments on the Google Code issue, the 123 stars on the Google Code issue a sign and push out a point release with *just* this fix if your master branch is not ready for release?

**Comment by dwt** [comment]
Let me please second this comment by @rbu. To us that is a really serious bug, and warrants a point release. So if you can't release master because of unrelated work, then please go for a point release.

**Comment by kdeanjohnson** [comment]
Please provide an ETA on the fix.

**Comment by lukeis** [comment]
this has been fixed already. If you're looking for when an official release is going to be made the answer is 'when it's ready'

**Comment by kramerdog** [comment]
Since when had open-source meant 'dont care about the users'? 3 months to release a fix for a serious issue caused by an update that impacts a large number of users is just contemptuous. A lot of respect has been lost as a result of the way this has been handled. 'Dont care' I hear you say again?

**Comment by lukeis** [comment]
we are more than happy to have more people join the community to help us get this released. If you've followed along on our IRC channel, you'll know that we do actually want to make a release, but it continues to be complicated by other factors and lack of people doing some of the leg work to make a release.

**Comment by kramerdog** [comment]
We're all developers here. I dont think anybody understands how it can be
so hard to release a patch that fixes the bug that has plagued us all for 3
months. Please enlighten us with why this is so complicated and
time-consuming and requires the efforts of a legion of helpers....

**Comment by duncan-bayne** [comment]
@lukeis how dare you delay the release of a vital project that all of us use, and none of us contribute to or pay for.  Shame on you :wink:

Seriously though: how can we help?  Are there GitHub issues that could be addressed by developers not particularly familiar with Selenium internals?  Docs to write?  Release notes?  Infrastructure to provide?

**Comment by cgoldberg** [comment]
@kramerdog I suggest you volunteer your time towards contributing.  Rather than standing on the sidelines complaining, you could actually help release quicker.  This is a community project.

Alternately, if you are unhappy with the current release cadence, feel free to fork the project and do your own releases.

**Comment by barancev** [comment]
The people who claim they are "developers" can download the source code and build selenium yourself, it is as easy as 'go release'.

It is also possible to download the latest selenium standalone Java distribution package from the CI server: http://ci.seleniumhq.org:8080/job/Build%20All%20Java/
(Sometimes "latest" is broken, watch the CI results and use it on your own risk)

Unfortunately (or fortunately) Selenium uses trunk-based development model, that's the reason why it is not so easy to launch a "patch release".

Be patient, or get the "latest" as described above, and pray is it stable enough.

**Comment by kramerdog** [comment]
Thanks for the wrist-slap @cgoldberg and I get the point which has been made many times before. I still dont think that being a 'community project' is an excuse for the way that this issue has been handled. All projects still come with responsibilities to users, community or not.

And I fail to understand how the argument that "it's so easy to build, why don't thousands of you go ahead and do it independently rather than the project doing it once" stands up to scrutiny.

The point is that all of the developers are busy doing their own projects and dont necessarily have the time or know-how to go delving into an aspect of Selenium that they didn't sign up for when they chose to use the product in the first place. Do you really expect all users to be hands-on with the development in order to justify their usage?

But thanks to @barancev for explaining why it is harder to create a patch than you would think. Seems like a bad choice of development model, but maybe that's just me.

**Comment by kkshieh** [comment]
Can we at least please get an estimated date for a release?  Even developers with project release community have those?

**Comment by lukeis** [comment]
@kkshieh sorry, but no, we can't provide anything the would resemble an accurate date. It could be today? It could be next month? We are actually honest developers contributing time on-the-side and don't believe a guess of a date is helpful in anyway or truthful.

We have some test failures in our CI system with firefox that still need to get figured out... and that is *hopefully* the last blocker to release.

**Comment by lqc** [comment]
@lukeis I think the main problem is purely communication based. For a developer not involved in the project, it's very hard to determine what are the release blockers and how they can help to resolve them. Two things that IMHO would help: 

1) For every blocker, create an issue with "I-blocker" label, so people know what is to be done.
2) Put a link to the CI in README, so it's easy to find

But maybe this discussion is better suited on the mailing list...

**Comment by jeremyr8r** [comment]
@kramerdog 
"Do you really expect all users to be hands-on with the development in order to justify their usage?"
Yes. You as a developer, if you are a developer, have the responsibility to do your job correctly. If a tool doesn't work for you then find a tool that does to get the job done. If there isn't a tool available it is still your responsibility to "develope" something.

**Comment by mhoofman** [comment]
For anyone subscribed to this issue and not yet aware, 2.46.0 has been released.

http://docs.seleniumhq.org/download/

**Comment by kramerdog** [comment]
So @jeremyr8r, I should be a hands-on developer for all the 50+ gems and
open-source software products I use? Not sure what world you live in?

**Comment by codener** [comment]
Thanks for the fix!

**Comment by gustahrodrigues** [comment]
Hello,

I'm facing the same slow issue using CentOs 6.6, Firefox 31.1.0, Selinum 2.48.0 (python) and Python 2.7.6.

Someone has some idea what's happening and how to fix it?

I'm already disabled javascript but did'nt fix it.

```
firefox_profile.set_preference("browser.download.folderList",2)
firefox_profile.set_preference("javascript.enabled", False)
```

**Comment by Azharmrd** [comment]
Thanks for the information. Want to get trained on Selenium? Mindmajix provides [best Selenium training](https://mindmajix.com/selenium-training). Online training by real time experts.
