### ISSUE TITLE
Boolean command line arguments should be `true` if present

### ISSUE THREAD

**Issue by stephenash** [SeleniumHQ/selenium#3877]
When launching a selenium server process using <= 3.0.1, the `-debug` command line argument was just a switch.

```shell
$> java 3.0.1-server.jar -debug
10:14:44.427 INFO - Selenium build info: version: '3.0.1', revision: '1969d75'
10:14:44.428 INFO - Launching a standalone Selenium Server
...
```

So the same command does not work with 3.1.0+.

```shell
$> java 3.1.0-server.jar -debug
Exception in thread "main" com.beust.jcommander.ParameterException: Expected a value after parameter -debug
        at com.beust.jcommander.JCommander.processFixedArity(JCommander.java:883)
        at com.beust.jcommander.JCommander.processFixedArity(JCommander.java:857)
        at com.beust.jcommander.JCommander.parseValues(JCommander.java:725)
        at com.beust.jcommander.JCommander.parse(JCommander.java:282)
        at com.beust.jcommander.JCommander.parse(JCommander.java:265)
        at com.beust.jcommander.JCommander.<init>(JCommander.java:210)
        at org.openqa.grid.selenium.GridLauncherV3$1.setConfiguration(GridLauncherV3.java:227)
        at org.openqa.grid.selenium.GridLauncherV3.buildLauncher(GridLauncherV3.java:155)
        at org.openqa.grid.selenium.GridLauncherV3.main(GridLauncherV3.java:75)
```

In order to get it to work again, a user must using something like

```shell
$> java 3.1.0-server.jar -debug true
10:19:12.394 INFO - Selenium build info: version: '3.1.0', revision: '86a5d70'
10:19:12.394 INFO - Launching a standalone Selenium Server
...
```

With https://github.com/SeleniumHQ/selenium/commit/705be71ce9ec7e3825cb1633d3da40ab75a8819f, that behavior was changed. That change was never called out in the release notes via the [CHANGELOG](https://github.com/SeleniumHQ/selenium/blob/4fcbef7f486d74a741a441482e0a1676f9d959ae/java/CHANGELOG) or in the [GitHub release](https://github.com/SeleniumHQ/selenium/releases/tag/selenium-3.1.0).

Can you please update the release notes to reflect the changes?

**Comment by shs96c** [comment]
I think it'd be better if we fixed the command line parsing to restore the expected behaviour --- that's not a deliberate change.

**Comment by barancev** [comment]
Fixed in version 3.5

**Comment by stephenash** [comment]
Thanks for the fix. The change in behavior (even from v3.4.0 to v3.5.0) is still not reflected in the [CHANGELOG.md](https://github.com/SeleniumHQ/selenium/blob/selenium-3.5.0/java/CHANGELOG).

Since that was part of my original issue, can we re-open this until that part is addressed as well?
