### ISSUE TITLE
WebDriverException when using Actions on InternetExplorer with selenium grid 3.5.0

### ISSUE THREAD

**Issue by anikulin** [SeleniumHQ/selenium#4473]
## Meta -
OS: Windows 10
Selenium Version:  3.5.0 (grid), 3.3.0 (client)
Browser:  Internet Explorer 11
Browser Version:  11.1593.14393.0 (64-bit)

## Expected Behavior -
Browser is expected to perform mouse actions
## Actual Behavior -
```
org.openqa.selenium.WebDriverException: <html>
<head>
<meta http-equiv="Content-Type" content="text/html;charset=utf-8"/>
<title>Error 500 Server Error</title>
</head>
<body><h2>HTTP ERROR 500</h2>
<p>Problem accessing /wd/hub/session/0130ad39-618b-456f-9d4f-2e122b6310ee/moveto. Reason:
<pre>    Server Error</pre></p><h3>Caused by:</h3><pre>java.lang.NullPointerException
	at com.google.gson.JsonPrimitive.isPrimitiveOrString(JsonPrimitive.java:278)
```
(full error log is attached)
[failed.txt](https://github.com/SeleniumHQ/selenium/files/1227677/failed.txt)

## Steps to reproduce -
1. Start local selenium grid (node + hub) using selenium-server-standalone-3.5.0.jar 
2. Run the following test case:
```
    @Test
    public void googleActionsTest() throws Exception {
        Capabilities cap = DesiredCapabilities.internetExplorer();
        WebDriver d = new RemoteWebDriver(new URL("http://localhost:4444/wd/hub"), cap);

        String page = "https://google.com";
        d.get(page);

        WebElement e = d.findElement(By.name("q"));

        new Actions(d).moveToElement(e).build().perform();

        d.quit();
    }
```

Works fine with Google Chrome as far as I tested it. Also worked fine with older selenium grid (2.53.1).

**Comment by shs96c** [comment]
This should be fixed by 88e08c8ae0b65970fda25b4b7e28bb862a73155e.

**Comment by anikulin** [comment]
Excuse me, I understand that the handling of null values makes things better, but **it does not solve the original problem**: now I got org.openqa.selenium.UnsupportedCommandException: mouseMoveTo intead of mouse moving.

Is it expected that the commandthat was supported in 2.53.1, become not supported in 3.5.0?

**Comment by jimevans** [comment]
@anikulin What version of `IEDriverServer.exe` are you using? It makes a big difference when discussing this particular issue. If you've updated to 3.5 of the IE driver, [you really should update](https://github.com/SeleniumHQ/selenium/blob/master/cpp/iedriverserver/CHANGELOG#L16) to 3.5 of the client language bindings.

**Comment by anikulin** [comment]
@jimevans, well, in fact I am not sure I understand correctly how this should work in the case of Selenium Grid.
If I've updated selenium-standalone and IEDriverServer to 3.5.0 on the Grid, shall I force all *remote* clients to also update their bindings to 3.5.0?
This is not the expected way of how shared Grid should work, from my point of view.

(not to mention that the 3.5.0 libraries even not available in the maven repository)

**Comment by jimevans** [comment]
@anikulin The IE driver is in a unique position at the moment. It's the first remote end implementation to migrate from the original OSS dialect of the wire protocol to the W3C dialect. The latter dialect has much stricter requirements on what is allowed to be in the JSON payloads of the commands, and in particular the new session command. Previous versions of the local end language bindings and of the grid do not properly format the command payloads according to those more restrictive requirements for IE. There is some inconvenience involved and for that I apologize. The decision was not made lightly, and there was a beta period for the IE driver which was widely promoted. The bottom line is that unless you can reproduce the issue with all components in the system (IEDriverServer.exe, grid hub, and nodes) at 3.5 or higher, there is nothing that can be done with this issue.

**Comment by barancev** [comment]
FYI: version 3.5.1 is available in maven central

**Comment by anikulin** [comment]
@jimevans, @barancev thank you for the information.
I just thought that there should be two separate chains of communication: one from client to the grid, abstracted from specific drivers, and other from grid node to the browser, so it would possible for different clients to work with the same grid.
