### ISSUE TITLE
Unable to create remote session with Firefox, using geckodriver 0.18.0 and selenium 3.5.1

### ISSUE THREAD

**Issue by pmadhuyadav** [SeleniumHQ/selenium#4498]
## Meta -
OS:  Windows 7

Selenium Version:  
Selenium :3.5.1 and selenium standalone server :3.5.1 
Browser:  
Firefox-54

Browser Version:  

## Expected Behavior -
Firefox browser should opened 
## Actual Behavior -
Unable to create to create firefox session with ScreenShotRemoteWebDriver
## Steps to reproduce -
Lunch hub and node with selenium standalone server 3.5.1
refer attached batch files to start hub and node

My code: IWebDriver webDriver = new ScreenShotRemoteWebDriver(new Uri("remote driver url"), (DesiredCapabilities) GetFirefoxOptions(properties).ToCapabilities(), TimeSpan.FromSeconds(300))
public static FirefoxOptions GetFirefoxOptions(WebDriverProperties properties)
        {
            var firefoxOptions = new FirefoxOptions();
            
                       firefoxOptions.SetPreference("network.automatic-ntlm-auth.allow-proxies", true);
            firefoxOptions.SetPreference("network.automatic-ntlm-auth.trusted-uris",
                "bedproxy201, bedproxy202, bedproxy203, bedproxy204, mayproxy101, mayproxy102, mayproxy103, malproxy101, bosproxy301, bosproxy302, bosproxy303, bedproxy205, bedproxy206, bedproxy207, bedproxy208, bedproxy209");
            return firefoxOptions;
        }

Log: 
An assertion failed.
System.InvalidOperationException: Unable to create new service: GeckoDriverService
Build info: version: '3.5.1', revision: '9c21bb67ef', time: '2017-08-16T21:10:06.092Z'
System info: host: 'MYKULWK1D7L862', ip: '10.216.108.62', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_60'
Driver info: driver.version: unknown (InsecureCertificate)
   at OpenQA.Selenium.Remote.RemoteWebDriver.UnpackAndThrowOnError(Response errorResponse)
   at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.Remote.RemoteWebDriver.StartSession(ICapabilities desiredCapabilities)
   at OpenQA.Selenium.Remote.RemoteWebDriver..ctor(ICommandExecutor commandExecutor, ICapabilities desiredCapabilities)

[runhub.txt](https://github.com/SeleniumHQ/selenium/files/1233763/runhub.txt)
[runnode.txt](https://github.com/SeleniumHQ/selenium/files/1233764/runnode.txt)

**Comment by jimevans** [comment]
And what is `ScreenshotRemoteWebDriver`? There are tests for the .NET bindings that create sessions via remote for all supported browsers, and they pass.

**Comment by barancev** [comment]
Please provide a [concise reproducible test case](http://sscce.org/)

**Comment by pmadhuyadav** [comment]
@jimevans 
ScreenshotRemoteWebDriver is a my customized class for  RemoteWebDriver
 public class ScreenShotRemoteWebDriver : RemoteWebDriver, ITakesScreenshot
    {
        public ScreenShotRemoteWebDriver(Uri remoteAdress, ICapabilities capabilities)
            : base(remoteAdress, capabilities)
        {
        }

        public ScreenShotRemoteWebDriver(Uri remoteAdress, ICapabilities capabilities, TimeSpan commandTimeout)
            : base(remoteAdress, capabilities, commandTimeout)
        {
        }
}

**Comment by pmadhuyadav** [comment]
Able to create remote session after added this into firefox options
var firefoxOptions = new FirefoxOptions();

            firefoxOptions.BrowserExecutableLocation = "C:\\Program Files\\Mozilla Firefox\\firefox.exe";

**Comment by Elufimov** [comment]
Why selenium need local firefox? Selenium 3.5.1 from nuget and on the grid.
```csharp
using System;
using System.Threading;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;

namespace ConsoleApplication
{
    internal class Program
    {
        public static void Main(string[] args)
        {
            var driver = new RemoteWebDriver(new Uri("http://192.168.0.51:4444/wd/hub"), new FirefoxOptions());
            driver.Navigate().GoToUrl("http://ya.ru");
            Thread.Sleep(3000);
            Console.WriteLine(driver.PageSource);
            driver.Quit();
        }
    }
}
```

```
Unhandled Exception: OpenQA.Selenium.WebDriverException: Cannot find Firefox binary in PATH or default install locations. Make sure Firefox is installed. OS appears to be: Vista
   at OpenQA.Selenium.Firefox.Internal.Executable..ctor(String userSpecifiedBinaryPath)
   at OpenQA.Selenium.Firefox.FirefoxBinary..ctor(String pathToFirefoxBinary)
   at OpenQA.Selenium.Firefox.FirefoxOptions.GenerateFirefoxOptionsDictionary()
   at OpenQA.Selenium.Firefox.FirefoxOptions.ToCapabilities()
   at OpenQA.Selenium.Remote.RemoteWebDriver.ConvertOptionsToCapabilities(DriverOptions options)
   at OpenQA.Selenium.Remote.RemoteWebDriver..ctor(Uri remoteAddress, DriverOptions options)
   at ConsoleApplication.Program.Main(String[] args) in C:\projects\Test\src\ConsoleApplication\Program.cs:line 14

```

**Comment by jimevans** [comment]
Then this has been fixed in d453c86.

**Comment by Elufimov** [comment]
I found this commit, but apparently it did not fix this error. I will appreciate if you will point me about what I am doing wrong.

**Comment by Elufimov** [comment]
Workaround for selenium docker images is 
```csharp
var option = new FirefoxOptions();
option.BrowserExecutableLocation = "/usr/bin/firefox";
var driver = new RemoteWebDriver(new Uri("http://192.168.0.51:4444/wd/hub"), option);
```
But why is it necessary in the first place?

**Comment by jimevans** [comment]
@Elufimov To answer your question, as of d453c86, it _isn't_ necessary any longer. You say that commit does not fix the issue, but how have you tried it? That commit has not been publicly released in a binary form, via NuGet or any other release mechanism; 3.5.1 of the .NET bindings does **not** include that commit. I know that commit solves the issue using the .NET bindings and the standalone server/grid in my environment.

**Comment by Elufimov** [comment]
I saw label selenium-3.5.1 and thought that this commit already included in 3.5.1 from nuget. Right now I understand that this is unrelated things. I also misunderstood your comment, because you said that it was fixed. Sorry for mislead. Do you have eta for next release?

**Comment by Elufimov** [comment]
Are there any news? Can anyone from selenium team publish a new version of .net binding?

**Comment by jimevans** [comment]
@Elufimov As I'm volunteering my time to this project, and indeed don't even use the .NET bindings in my day-to-day work that I get paid for, I have no time table for pushing a new release. As it happens, I've been away from all work for the last several days, and probably won't get around to it today. It will get released when I get the chance to push one or coordinate with the rest of the project for a larger project-wide release. Continuing to ask for updates is most assuredly not the way to make that release happen any faster. There is no further news, and there won't be any further news until the release is actually done.

**Comment by Elufimov** [comment]
Do not get me wrong. I am very grateful for your time that you contribute to the community. Supporting such big project alone is very hard. I thought there is a ci and publishing is a matter of clicking button.

**Comment by barancev** [comment]
Selenium 3.6 released, please check that issue has been fixed.

**Comment by Elufimov** [comment]
Yes, it was fixed in 3.5.2.
