### ISSUE TITLE
Hang when executing driver.implicitly_wait()

### ISSUE THREAD

**Issue by PhilippSelenium** [SeleniumHQ/selenium#4620]
## Meta -
OS:  
Windows 7
Selenium Version:  
3.5.1
Browser:  
Internet Explorer
Browser Version:  
IE 11 (64-bit)

## Expected Behavior -
Executing implicitly_wait retruns successfully

## Actual Behavior -
Executing implicitly_wait crashes IEDriverServer

## Steps to reproduce -
I am using the newest Selenium Standalone Server (3.5.3) and the newest IEDriverServer (3.5.1) on Win7 IE11 
The Language Binding is selenium for python 3.5

### remote
from selenium import webdriver
driver = webdriver.Remote(command_executor='http://192.168.61.143:4444/wd/hub', desired_capabilities=webdriver.DesiredCapabilities().INTERNETEXPLORER)
driver.implicitly_wait(10)

### locally
from selenium import webdriver
driver = webdriver.Ie()
driver.implicitly_wait(10)

## Crash report from IE 11

Problem signature:
  Problem Event Name:	APPCRASH
  Application Name:	IEDriverServer.exe
  Application Version:	3.5.1.0
  Application Timestamp:	599626e6
  Fault Module Name:	IEDriverServer.exe
  Fault Module Version:	3.5.1.0
  Fault Module Timestamp:	599626e6
  Exception Code:	40000015
  Exception Offset:	00000000000180c2
  OS Version:	6.1.7601.2.1.0.256.4
  Locale ID:	1033
  Additional Information 1:	8271
  Additional Information 2:	82715b74f26df034939cd7f798206b31
  Additional Information 3:	e101
  Additional Information 4:	e101d7a790c4cb23464a30fc4d3dc859
 
## Additional Information
Works fine for firefox gecko driver 0.18.0 and IEDriverServer v3.0 with same setup.

**Comment by barancev** [comment]
Start remote server with extra options to collect IE driver logs:
```
java -Dwebdriver.ie.driver.logfile=iedriver.log -Dwebdriver.ie.driver.loglevel=TRACE -jar selenium-server-standalone-3.5.3.jar
```
run your scenario and attach the collected log file here.

**Comment by PhilippSelenium** [comment]
I 2017-09-04 08:14:48:619 server.cc(86) Starting WebDriver server on port: '35798' on host: ''
T 2017-09-04 08:14:48:619 server.cc(634) Entering Server::PopulateCommandRepository
T 2017-09-04 08:14:48:619 IEServer.cpp(32) Entering IEServer::IEServer
I 2017-09-04 08:14:48:619 IEServer.cpp(33) Driver version: 3.5.1.0 (64-bit)
T 2017-09-04 08:14:48:619 server.cc(121) Entering Server::Start
D 2017-09-04 08:14:48:619 server.cc(148) Civetweb ACL is -0.0.0.0/0,+127.0.0.1
T 2017-09-04 08:14:48:994 server.cc(174) Entering Server::ProcessRequest
T 2017-09-04 08:14:48:994 server.cc(183) Process request with: URI: /status HTTP verb: GET
body: {}
T 2017-09-04 08:14:48:994 server.cc(272) Entering Server::DispatchCommand
T 2017-09-04 08:14:48:994 server.cc(583) Entering Server::LookupCommand
D 2017-09-04 08:14:48:994 server.cc(281) Command: GET /status {}
T 2017-09-04 08:14:48:994 IEServer.cpp(51) Entering IEServer::GetStatus
T 2017-09-04 08:14:48:994 response.cc(72) Entering Response::SetSuccessResponse
T 2017-09-04 08:14:48:994 response.cc(78) Entering Response::SetResponse
T 2017-09-04 08:14:48:994 response.cc(51) Entering Response::Serialize
D 2017-09-04 08:14:48:994 server.cc(338) Response: {"value":{"build":{"version":"3.5.1.0 (64-bit)"},"os":{"arch":"x64","name":"windows","version":"6.1.7601.18015 (win7sp1_gdr.121129-1432)"}}}

T 2017-09-04 08:14:48:994 server.cc(391) Entering Server::SendResponseToClient
T 2017-09-04 08:14:48:994 response.cc(30) Entering Response::Deserialize
T 2017-09-04 08:14:48:994 server.cc(445) Entering Server::SendHttpOk
T 2017-09-04 08:14:49:587 server.cc(174) Entering Server::ProcessRequest
T 2017-09-04 08:14:49:587 server.cc(238) Entering Server::ReadRequestBody
T 2017-09-04 08:14:49:587 server.cc(183) Process request with: URI: /session HTTP verb: POST
body: {"capabilities":{"firstMatch":[{}],"alwaysMatch":{"browserName":"internet explorer"}},"desiredCapabilities":{"browserName":"internet explorer","version":"","platform":"WINDOWS"}}
T 2017-09-04 08:14:49:587 server.cc(272) Entering Server::DispatchCommand
T 2017-09-04 08:14:49:587 server.cc(583) Entering Server::LookupCommand
D 2017-09-04 08:14:49:587 server.cc(281) Command: POST /session {"capabilities":{"firstMatch":[{}],"alwaysMatch":{"browserName":"internet explorer"}},"desiredCapabilities":{"browserName":"internet explorer","version":"","platform":"WINDOWS"}}
T 2017-09-04 08:14:49:587 IEServer.cpp(42) Entering IEServer::InitializeSession
T 2017-09-04 08:14:49:587 IESession.cpp(38) Entering IESession::Initialize
D 2017-09-04 08:14:49:587 IESession.cpp(53) Mutex acquired for session initalization
T 2017-09-04 08:14:49:587 IECommandExecutor.cpp(386) Entering IECommandExecutor::ThreadProc
T 2017-09-04 08:14:49:587 IECommandExecutor.cpp(47) Entering IECommandExecutor::OnCreate
T 2017-09-04 08:14:49:587 IECommandExecutor.cpp(743) Entering IECommandExecutor::PopulateElementFinderMethods
T 2017-09-04 08:14:49:603 InputManager.cpp(40) Entering InputManager::InputManager
T 2017-09-04 08:14:49:603 InputManager.cpp(75) Entering InputManager::Initialize
T 2017-09-04 08:14:49:603 BrowserFactory.cpp(998) Entering BrowserFactory::GetExecutableLocation
T 2017-09-04 08:14:49:603 BrowserFactory.cpp(1039) Entering BrowserFactory::GetIEVersion
T 2017-09-04 08:14:49:603 CommandHandlerRepository.cpp(104) Entering CommandHandlerRepository::PopulateCommandHandlers
T 2017-09-04 08:14:49:603 IESession.cpp(99) Created thread for command executor returns HWND: '0000000000050164'
T 2017-09-04 08:14:49:603 IESession.cpp(103) Session id is retrived from command executor window: 'c65b1174-89d0-4e1d-95ef-8b4077da3bfe'
D 2017-09-04 08:14:49:603 IESession.cpp(109) Releasing session initialization mutex
T 2017-09-04 08:14:49:603 IESession.cpp(191) Entering IESession::ExecuteCommand
T 2017-09-04 08:14:49:603 IECommandExecutor.cpp(122) Entering IECommandExecutor::OnSetCommand
T 2017-09-04 08:14:49:603 command.cc(31) Entering Command::Deserialize
D 2017-09-04 08:14:49:603 command.cc(36) Raw JSON command: { "name" : "newSession", "locator" : { }, "parameters" : {"capabilities":{"firstMatch":[{}],"alwaysMatch":{"browserName":"internet explorer"}},"desiredCapabilities":{"browserName":"internet explorer","version":"","platform":"WINDOWS"}} }
T 2017-09-04 08:14:49:603 IECommandExecutor.cpp(133) Entering IECommandExecutor::OnExecCommand
T 2017-09-04 08:14:49:603 IECommandExecutor.cpp(454) Entering IECommandExecutor::DispatchCommand
T 2017-09-04 08:14:49:603 BrowserFactory.cpp(113) Entering BrowserFactory::Initialize
T 2017-09-04 08:14:49:603 IECommandExecutor.cpp(621) Entering IECommandExecutor::CreateNewBrowser
T 2017-09-04 08:14:49:603 BrowserFactory.cpp(142) Entering BrowserFactory::LaunchBrowserProcess
D 2017-09-04 08:14:49:603 BrowserFactory.cpp(146) Ignoring Protected Mode Settings: 0
D 2017-09-04 08:14:49:603 BrowserFactory.cpp(149) Checking validity of Protected Mode settings.
T 2017-09-04 08:14:49:603 BrowserFactory.cpp(1058) Entering BrowserFactory::ProtectedModeSettingsAreValid
D 2017-09-04 08:14:49:603 BrowserFactory.cpp(1061) Detected IE version: 11, Windows version supports Protected Mode: 1
T 2017-09-04 08:14:49:603 BrowserFactory.cpp(1135) Entering BrowserFactory::GetZoneProtectedModeSetting
D 2017-09-04 08:14:49:603 BrowserFactory.cpp(1152) Found Protected Mode setting value of 3 for zone 1
T 2017-09-04 08:14:49:603 BrowserFactory.cpp(1135) Entering BrowserFactory::GetZoneProtectedModeSetting
D 2017-09-04 08:14:49:603 BrowserFactory.cpp(1152) Found Protected Mode setting value of 3 for zone 2
T 2017-09-04 08:14:49:603 BrowserFactory.cpp(1135) Entering BrowserFactory::GetZoneProtectedModeSetting
D 2017-09-04 08:14:49:603 BrowserFactory.cpp(1152) Found Protected Mode setting value of 3 for zone 3
T 2017-09-04 08:14:49:603 BrowserFactory.cpp(1135) Entering BrowserFactory::GetZoneProtectedModeSetting
D 2017-09-04 08:14:49:603 BrowserFactory.cpp(1152) Found Protected Mode setting value of 3 for zone 4
D 2017-09-04 08:14:49:603 BrowserFactory.cpp(152) Has Valid Protected Mode Settings: 1
T 2017-09-04 08:14:49:603 BrowserFactory.cpp(226) Entering BrowserFactory::IsIELaunchURLAvailable
T 2017-09-04 08:14:49:619 BrowserFactory.cpp(130) Entering BrowserFactory::ClearCache
T 2017-09-04 08:14:49:619 BrowserFactory.cpp(247) Entering BrowserFactory::LaunchBrowserUsingIELaunchURL
D 2017-09-04 08:14:49:619 BrowserFactory.cpp(248) Starting IE using the IELaunchURL API
T 2017-09-04 08:14:50:166 IESession.cpp(212) Beginning wait for response length to be not zero
D 2017-09-04 08:14:50:166 BrowserFactory.cpp(202) IE launched successfully with process ID 2588
D 2017-09-04 08:14:50:166 BrowserFactory.cpp(208) Process with ID 2588 is executing iexplore.exe
T 2017-09-04 08:14:50:166 BrowserFactory.cpp(365) Entering BrowserFactory::AttachToBrowser
D 2017-09-04 08:14:50:166 BrowserFactory.cpp(375) Using Active Accessibility to find IWebBrowser2 interface
T 2017-09-04 08:14:50:166 BrowserFactory.cpp(414) Entering BrowserFactory::AttachToBrowserUsingActiveAccessibility
T 2017-09-04 08:14:51:494 server.cc(174) Entering Server::ProcessRequest
T 2017-09-04 08:14:51:494 server.cc(183) Process request with: URI: / HTTP verb: GET
body: {}
T 2017-09-04 08:14:51:494 server.cc(445) Entering Server::SendHttpOk
D 2017-09-04 08:14:51:916 BrowserFactory.cpp(434) Found window handle 00000000000101DE for window with class 'Internet Explorer_Server' belonging to process with id 2588
T 2017-09-04 08:14:51:916 BrowserFactory.cpp(329) Entering BrowserFactory::GetDocumentFromWindowHandle
T 2017-09-04 08:14:52:244 server.cc(174) Entering Server::ProcessRequest
T 2017-09-04 08:14:52:259 server.cc(183) Process request with: URI: /favicon.ico HTTP verb: GET
body: {}
T 2017-09-04 08:14:52:259 server.cc(272) Entering Server::DispatchCommand
T 2017-09-04 08:14:52:259 server.cc(583) Entering Server::LookupCommand
D 2017-09-04 08:14:52:259 server.cc(281) Command: GET /favicon.ico {}
D 2017-09-04 08:14:52:259 server.cc(338) Response: { "error" : "unknown method", "message" : "Command not found: GET /favicon.ico" }
T 2017-09-04 08:14:52:259 server.cc(391) Entering Server::SendResponseToClient
T 2017-09-04 08:14:52:259 response.cc(30) Entering Response::Deserialize
T 2017-09-04 08:14:52:259 server.cc(445) Entering Server::SendHttpOk
D 2017-09-04 08:14:52:494 BrowserFactory.cpp(396) Ignoring zoom setting: 0
T 2017-09-04 08:14:52:494 BrowserFactory.cpp(574) Entering BrowserFactory::GetBrowserZoomLevel
T 2017-09-04 08:14:52:509 BrowserFactory.cpp(614) Entering BrowserFactory::GetZoomLevel
D 2017-09-04 08:14:52:525 BrowserFactory.cpp(694) Browser zoom level is 100%
I 2017-09-04 08:14:52:525 IECommandExecutor.cpp(644) Persistent hovering set to: 1
T 2017-09-04 08:14:52:525 ProxyManager.cpp(95) ProxyManager::SetProxySettings
D 2017-09-04 08:14:52:525 ProxyManager.cpp(111) Using existing system proxy settings.
T 2017-09-04 08:14:52:525 DocumentHost.cpp(33) Entering DocumentHost::DocumentHost
T 2017-09-04 08:14:52:525 CookieManager.cpp(49) Entering CookieManager::Initialize
T 2017-09-04 08:14:52:525 Browser.cpp(33) Entering Browser::Browser
T 2017-09-04 08:14:52:525 Browser.cpp(293) Entering Browser::AttachEvents
T 2017-09-04 08:14:52:525 IECommandExecutor.cpp(611) Entering IECommandExecutor::AddManagedBrowser
T 2017-09-04 08:14:52:525 IECommandExecutor.cpp(615) Setting current browser id to 8291b379-99ff-485d-8d6c-5e2122cbcea8
T 2017-09-04 08:14:52:525 response.cc(72) Entering Response::SetSuccessResponse
T 2017-09-04 08:14:52:525 response.cc(78) Entering Response::SetResponse
T 2017-09-04 08:14:52:525 IECommandExecutor.cpp(567) Entering IECommandExecutor::GetCurrentBrowser
T 2017-09-04 08:14:52:525 IECommandExecutor.cpp(573) Entering IECommandExecutor::GetManagedBrowser
T 2017-09-04 08:14:52:525 response.cc(51) Entering Response::Serialize
T 2017-09-04 08:14:52:541 IESession.cpp(221) Found non-zero response length
T 2017-09-04 08:14:52:541 IECommandExecutor.cpp(156) Entering IECommandExecutor::OnGetResponse
T 2017-09-04 08:14:52:541 IECommandExecutor.cpp(285) Entering IECommandExecutor::OnIsSessionValid
T 2017-09-04 08:14:52:541 response.cc(30) Entering Response::Deserialize
D 2017-09-04 08:14:52:541 server.cc(338) Response: {"value":{"capabilities":{"acceptInsecureCerts":false,"browserName":"internet explorer","browserVersion":"11","pageLoadStrategy":"normal","platformName":"windows","se:ieOptions":{"browserAttachTimeout":0,"elementScrollBehavior":0,"enablePersistentHover":true,"ie.browserCommandLineSwitches":"","ie.ensureCleanSession":false,"ie.fileUploadDialogTimeout":3000,"ie.forceCreateProcessApi":false,"ignoreProtectedModeSettings":false,"ignoreZoomSetting":false,"initialBrowserUrl":"http://localhost:35798/","nativeEvents":true,"requireWindowFocus":false},"setWindowRect":true,"unhandledPromptBehavior":"dismiss"},"sessionId":"c65b1174-89d0-4e1d-95ef-8b4077da3bfe"}}

T 2017-09-04 08:14:52:541 server.cc(391) Entering Server::SendResponseToClient
T 2017-09-04 08:14:52:541 response.cc(30) Entering Response::Deserialize
T 2017-09-04 08:14:52:541 server.cc(445) Entering Server::SendHttpOk
T 2017-09-04 08:15:10:462 server.cc(174) Entering Server::ProcessRequest
T 2017-09-04 08:15:10:462 server.cc(238) Entering Server::ReadRequestBody
T 2017-09-04 08:15:10:462 server.cc(183) Process request with: URI: /session/c65b1174-89d0-4e1d-95ef-8b4077da3bfe/timeouts HTTP verb: POST
body: {"sessionId": "c65b1174-89d0-4e1d-95ef-8b4077da3bfe", "implicit": 10000}
T 2017-09-04 08:15:10:462 server.cc(272) Entering Server::DispatchCommand
T 2017-09-04 08:15:10:462 server.cc(583) Entering Server::LookupCommand
D 2017-09-04 08:15:10:462 server.cc(281) Command: POST /session/c65b1174-89d0-4e1d-95ef-8b4077da3bfe/timeouts {"sessionId": "c65b1174-89d0-4e1d-95ef-8b4077da3bfe", "implicit": 10000}
T 2017-09-04 08:15:10:462 server.cc(378) Entering Server::LookupSession
T 2017-09-04 08:15:10:462 IESession.cpp(191) Entering IESession::ExecuteCommand
T 2017-09-04 08:15:10:462 IECommandExecutor.cpp(122) Entering IECommandExecutor::OnSetCommand
T 2017-09-04 08:15:10:462 command.cc(31) Entering Command::Deserialize
D 2017-09-04 08:15:10:462 command.cc(36) Raw JSON command: { "name" : "setTimeouts", "locator" : { "sessionid" : "c65b1174-89d0-4e1d-95ef-8b4077da3bfe" }, "parameters" : {"sessionId": "c65b1174-89d0-4e1d-95ef-8b4077da3bfe", "implicit": 10000} }
T 2017-09-04 08:15:10:462 IECommandExecutor.cpp(133) Entering IECommandExecutor::OnExecCommand
T 2017-09-04 08:15:10:462 IECommandExecutor.cpp(454) Entering IECommandExecutor::DispatchCommand
T 2017-09-04 08:15:10:462 IECommandExecutor.cpp(567) Entering IECommandExecutor::GetCurrentBrowser
T 2017-09-04 08:15:10:462 IECommandExecutor.cpp(573) Entering IECommandExecutor::GetManagedBrowser
T 2017-09-04 08:15:10:462 IECommandExecutor.cpp(523) Entering IECommandExecutor::IsAlertActive
T 2017-09-04 08:15:10:462 Browser.cpp(713) Entering Browser::GetActiveDialogWindowHandle
T 2017-09-04 08:15:10:462 Browser.cpp(206) Entering Browser::GetContentWindowHandle
D 2017-09-04 08:15:10:462 IECommandExecutor.cpp(537) No alert handle is found
T 2017-09-04 08:15:10:462 IESession.cpp(212) Beginning wait for response length to be not zero

**Comment by PhilippSelenium** [comment]
Friendly Ping: Issue still exists for version 3.6.0 independent of remote or local execution.

**Comment by PhilippSelenium** [comment]
Additional Information:
This started happening for IEDriverServer.exe 3.5.0 (All versions before are fine)
Happens also on windows 10

Is there any way to get information (logs) from the IEDriverServer.exe when running it locally?

@barancev: Can you reproduce this issue? Do you need more information?

**Comment by barancev** [comment]
I can't reproduce the issue. Maybe @jimevans can help with log analysis.

**Comment by PhilippSelenium** [comment]
I'm sorry but i cannot attach a coredump the files are too big to upload even when compressed.

**Comment by PhilippSelenium** [comment]
I tried to debug the code using visual studio but i do not have the debug symbols. 
Can they be downloaded, built somewhere?

The result without debug symbols:
Not Flagged > 13296	0 Worker Thread IEDCCB8.tmp thread IEDCCB8.tmp!000007fef30f230b Normal

**Comment by lmtierney** [comment]
@PhilippSelenium I believe this was fixed in IE Driver `3.7.0`, can you try with the latest?

**Comment by PhilippSelenium** [comment]
Nope issue still exists for 3.7 I would like to uplaod the dumps but they are too big even compressed.

**Comment by PhilippSelenium** [comment]
Hey we made some progress here for version 3.8.0 the driver does not crash anymore on implicit wait.
However executing:

driver.implicitly_wait(10)

now throws the following error:
InvalidArgumentException: Message: Invalid timeout type specified: sessionId

**Comment by jimevans** [comment]
Yes. That’s a bug in the python bindings. They should not be sending `sessionId` as a parameter in the payload.

**Comment by dev-e** [comment]
So, is there any workaround for python bindings v3.8?

**Comment by hiiwave** [comment]
This problem stills happens to me with v3.8. `driver.implicitly_wait(10)` throws the following error:
`InvalidArgumentException: Message: Invalid timeout type specified: sessionId`

Could you consider reopening this issue?

**Comment by cburkins** [comment]
Any word on a fix for this ?  I'm experiencing the same issue.

**Comment by lmtierney** [comment]
The fix for this would have been in `3.8.1`. Please try that version and report back

**Comment by cburkins** [comment]
Thank-you, upgrading selenium to 3.8.1 fixed the issue for me.
