### ISSUE TITLE
ActionChains.reset_actions() does not actually reset stored actions for Firefox

### ISSUE THREAD

**Issue by yugokato** [SeleniumHQ/selenium#6138]
## Meta -
OS:  Linux (Ubuntu 16.04)

Selenium Version:  3.13.0

Browser:  Firefox

Browser Version:  61.0.1 (geckodriver 0.21.0)

## Expected Behavior -
ActionChains.reset_actions() rests actions stored on the remote end

## Actual Behavior -
ActionChains.reset_actions() does not reset actions stored on the remote end. Because of this issue, old actions stored  before running reset_actions() are prepended to new actions stored after running reset_actions()

## Steps to reproduce -
(Example with minimum code)

```python
from selenium import webdriver
from selenium.webdriver import ActionChains
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

capabilities = DesiredCapabilities.FIREFOX.copy()
driver = webdriver.Remote(command_executor='http://<IP_ADDRESS>:4444/wd/hub', desired_capabilities=capabilities)
driver.get('http://www.google.com')
action_chains = ActionChains(driver)
action_chains.send_keys('a').perform()
action_chains.reset_actions()
action_chains.send_keys('a').perform()
```

After the last line of the code, 'aa' will be sent instead of 'a'.
This issue does not occur for Chrome.

**Comment by netzulo** [comment]
interesting... checking!

**Comment by cgoldberg** [comment]
@netzulo, stop spamming the issue tracker with useless unrelated comments!!!

**Comment by lmtierney** [comment]
The issue is that for `w3c` drivers it is not resetting the `_actions` stored in the ActionChains instance. It does, in fact, send the reset to the remote end. The code should be updated to also clear the actions stored since that is what it does for non-w3c drivers. There's already a separate command to `clear_actions` in the ActionBuilder just for the remote end on a `w3c` driver.

**Comment by lmtierney** [comment]
This has been fixed in 913261c63165e9393f60318b2bc580ddafd4a85b and will be in the next release

**Comment by jklingen92** [comment]
I'm still having this exact same issue. My source code is updated to the commit that you mentioned, but the actions are still stacking.

**Comment by lmtierney** [comment]
@jklingen92 if you're having an issue, please create a new issue with a reproducible scenario
