### ISSUE TITLE
ActionChains.reset_actions() does not reset actions.

### ISSUE THREAD

**Issue by jklingen92** [SeleniumHQ/selenium#6837]
## 🐛 Bug Report

The ActionChains.reset_actions() does not reset actions.

This is similar to issue  #6138 which has been closed.

## To Reproduce

Run the following code from the command line in Python
```
from time import sleep

from selenium import webdriver
from selenium.webdriver import ActionChains


def action_chains_test():
    driver = webdriver.Firefox()
    driver.get('https://developer.mozilla.org/en-US/')

    input = driver.find_element_by_id('home-q')

    mouse = ActionChains(driver)

    for x in range(5):
        mouse.click(input)
        mouse.send_keys('0')
        mouse.perform()
        print('Input is %s' % input.get_property('value'))
        sleep(3)
        input.clear()
        mouse.reset_actions()

    driver.close()


if __name__ == "__main__":
    action_chains_test()

```

Detailed steps to reproduce the behavior:

Run the above file. It will type a `0`, pause, type two `0`s, pause, type three `0`s (mine overwrites itself because of the click, which for some reason behaves like a double click), etc.

reset_actions never has any effect.

## Expected behavior

It should type a `0` into the input field, pause and then clear the input again.
It should do this 5 times.

## Test script or set of commands reproducing this issue

`python tmp.py`

## Environment

OS: Linux pop-os 4.18.0-13-generic
Browser: Firefox
Browser version: 64.0
Browser Driver version: GeckoDriver 0.23.0
Language Bindings version: Python 3.141.0

**Comment by lmtierney** [comment]
Thank you for the bug report. It seems we need to clear actions from each `ActionBuilder.devices` for `w3c`

**Comment by jklingen92** [comment]
Any progress on this?

**Comment by barancev** [comment]
As far as I can see it is already fixed by commit 913261c63165e9393f60318b2bc580ddafd4a85b
@lmtierney Can you please confirm or decline this?

**Comment by lmtierney** [comment]
Sorry, no this doesn't completely resolve it. We need to call the `clear_actions` method (https://github.com/SeleniumHQ/selenium/blob/master/py/selenium/webdriver/common/actions/input_device.py#L39-L40) for each `w3c` device in order for this to match behavior with OSS

**Comment by popdrummer** [comment]
Any progress now?  I have face the same question。

**Comment by lmtierney** [comment]
Hi sorry for the late response, this is addressed in f61e76bb591801bc8f2c6959aba100c6237133fc and will be in the next release

**Comment by ArthurGIT2017** [comment]
ActionBuilder class clear_actions() is causing this bug.

 def clear_actions(self):
        """
            Clears actions that are already stored on the remote end
        """
        self.driver.execute(Command.W3C_CLEAR_ACTIONS)
