### ISSUE TITLE
CapabilityType.LOGGING_PREFS is not valid for latest versions of Chrome (75+)

### ISSUE THREAD

**Issue by SlavikCA** [SeleniumHQ/selenium#7342]
## 🐛 Bug Report

Currently String LOGGING_PREFS is set to "loggingPrefs":
https://github.com/SeleniumHQ/selenium/blob/master/java/client/src/org/openqa/selenium/remote/CapabilityType.java#L52

I know, it was working in Chrome 71.
But it doesn't work in Chrome 75.
Chrome 75 only works when I manually use `'goog:loggingPrefs'` instead of `'loggingPrefs'`

## To Reproduce

Here is Groovy code, which is working (returns browser logs) with Chrome 71, but returns nothing with Chrome 75:
```Groovy
            ChromeOptions options = new ChromeOptions().addArguments(
                    '--headless',
                    '--no-sandbox',
                    '--disable-extensions')
            LoggingPreferences logPrefs = new LoggingPreferences()
            logPrefs.enable(LogType.BROWSER, Level.ALL)
            options.setCapability(CapabilityType.LOGGING_PREFS, logPrefs)
            driver = new ChromeDriver(options)
            driver.get(Endpoints.TAGGED_PAGE_URL)
            LogEntries logs = driver.manage().logs().get(LogType.BROWSER)
            for (LogEntry entry : logs) {
                log.info entry.message
           }
```
## Expected behavior
if i replace one line in the example above, it works in Chrome 75:
```Groovy
            options.setCapability('goog:loggingPrefs', logPrefs)
```

## Environment

OS: Mac Os Mojave
Browser: Chrome 75
Browser version: 75.0.3770.100 
Browser Driver version: chromedriver 75.0.3770.8
Language Bindings version: 
```
    compile 'org.seleniumhq.selenium:selenium-java:3.14.0'
    compile 'org.seleniumhq.selenium:selenium-api:3.14.0'
    compile 'org.seleniumhq.selenium:selenium-chrome-driver:3.14.0'
```
Selenium Grid version (if applicable): n/a, using local headless Chrome

**Comment by SlavikCA** [comment]
Looks to be related to https://github.com/SeleniumHQ/selenium/issues/7300

**Comment by SlavikCA** [comment]
Looks like issue us caused to by this:
https://bugs.chromium.org/p/chromedriver/issues/detail?id=2536

ChangeLog says:
http://chromedriver.chromium.org/downloads
```
ChromeDriver now runs in W3C standard compliant mode by default...
- Renamed capability loggingPrefs to goog:loggingPrefs, as required by W3C standard
```

**Comment by MatthewSteeples** [comment]
Workaround code for C# (until the library is fixed). This will update the value of the preference string as long as it's run before you make use of the options

`typeof(CapabilityType).GetField(nameof(CapabilityType.LoggingPreferences), BindingFlags.Static | BindingFlags.Public).SetValue(null, "goog:loggingPrefs");`

**Comment by barancev** [comment]
Fixed by commits 85e17c1579cc9efb77f90aace1157f6f403e3f3e and 51b6b33e0897848ccdf3f25413e0ba45728f2c74

**Comment by bcexopolllo** [comment]
> Fixed by commits [85e17c1](https://github.com/SeleniumHQ/selenium/commit/85e17c1579cc9efb77f90aace1157f6f403e3f3e) and [51b6b33](https://github.com/SeleniumHQ/selenium/commit/51b6b33e0897848ccdf3f25413e0ba45728f2c74)

Hi guys!
I still have an issue with the same version: v76 for C#:

driver.Manage().Logs.GetLog(LogType.Browser);

throws the 'object reference not set' exception.

should I report/create separate ticket for that?

**Comment by jimevans** [comment]
@bcexopolllo Please don’t open another issue report. It has been fixed in the .NET bindings already, and will be released in the forthcoming 4.0 alpha 3 release (there is no definitive time table for the release).

**Comment by bcexopolllo** [comment]
I really hope you guys will release it in nearest future! A lot of people waiting for a enhancements! 
Thanks for keeping maintain it!
