### ISSUE TITLE
Cannot Create Edge Driver

### ISSUE THREAD

**Issue by gfinzerScotts** [SeleniumHQ/selenium#7992]
## 🐛 Bug Report

I am unable to create an Edge Driver.  The driver the error says to download is not available for download.

## To Reproduce

```typescript
static async CreateEdgeDriverTry1():Promise<WebDriver>
{      
	var service = new edge.ServiceBuilder()
	.setPort(5555)
	.build();

	var options = new edge.Options();
	// configure browser options ...

	var driver = edge.Driver.createSession(options, service);

	return driver;
}
```

```typescript
static async CreateEdgeDriverTry2():Promise<WebDriver>
{      
	var driver = await new Builder().forBrowser("edge").build();

	return driver;
}
```

**It throws this error:**
Error: The MicrosoftWebDriver.exe could not be found on the current PATH. Please download the latest version of the MicrosoftEdgeDriver from https://www.microsoft.com/en-us/download/details.aspx?id=48212 and ensure it can be found on your PATH.

**When I go to that download page, the page says:**
*We're sorry, this download is no longer available.*

## Expected behavior

The driver can be created

## Test script or set of commands reproducing this issue

See above

## More Information
* I have both msedgedriver.exe and IEDriverServer.exe in my path that I downloaded from here:  https://developer.microsoft.com/en-us/microsoft-edge/tools/webdriver/
* I noticed in your selenium-webdriver/edge.js file that the EDGEDRIVER_EXE is MicrosoftWebDriver.exe
    * I tried changing it to msedgedriver.exe and that did not help either.

## Environment

* **OS:** Windows 10
* **Browser:** Microsoft Edge 
* **Browser version:** 44.17763.831.0
* **Browser Driver version:** 81.0.411.0 
* **Language Bindings version:** nodejs selenium-webdriver 4.0.0-alpha.5 
* **Selenium Grid version (if applicable):** n/a

**Comment by netzulo** [comment]
only need the binary? , then take a look https://github.com/netzulo/qadrivers#edge

**Comment by AutomatedTester** [comment]
This has recently been fixed in the master branch

**Comment by gfinzerScotts** [comment]
Still the same problem with 4.0.0-alpha.7

Error: The WebDriver for Edge could not be found on the current PATH. Please download the latest version of MicrosoftWebDriver.exe from https://developer.microsoft.com/en-us/microsoft-edge/tools/webdriver/ and ensure it can be found on your PATH.
      at new ServiceBuilder (node_modules\selenium-webdriver\edge.js:176:13)
      at createServiceFromCapabilities (node_modules\selenium-webdriver\edge.js:224:10)
      at Function.createSession (node_modules\selenium-webdriver\edge.js:241:34)
      at createDriver (node_modules\selenium-webdriver\index.js:155:33)
      at Builder.build (node_modules\selenium-webdriver\index.js:685:16)

I have both of these files in my path:
edgedriver_64.exe
msedgedriver.exe

I downloaded edgedriver_64 from here:  https://github.com/netzulo/qadrivers#edge

I downloaded msedgedriver.exe from here:  https://developer.microsoft.com/en-us/microsoft-edge/tools/webdriver/
