### ISSUE TITLE
Content-Type header is missing

### ISSUE THREAD

**Issue by connelhooley** [SeleniumHQ/selenium#8655]
## 💥 Regression Report

I cannot use `RemoteWebDriver` in C# at all with the latest alphas. Apologies if this is a known issue, I can't see anything so figured I'd report it. Seems like quite a fundamental issue though so maybe I'm missing something.

## Last working Selenium version

Not sure what this means, the docker images go up to alpha 7, the nuget package only goes up to 5. Below are the Nuget package versions:

Worked up to version:
3.141.0

Stopped working in version:
4.0.0-alpha01-4.0.0-alpha05 (I can't seem to get any v4 packages working, different errors on each version)

## To Reproduce

Run docker compose using the file documented here:
https://github.com/SeleniumHQ/docker-selenium/blob/trunk/docker-compose-v3.yml

```
dotnet new console -o "Example"
cd ./Example
dotnet add package Selenium.Support --version 4.0.0-alpha05 
dotnet add package Selenium.Selenium.WebDriver --version 4.0.0-alpha05 
```

Inside program.cs:
``` csharp
using System;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Remote;

namespace Example
{
    class Program
    {
        static void Main()
        {
            new RemoteWebDriver(new Uri("http://localhost:4444"), new ChromeOptions());
            Console.WriteLine("Done!");
        }
    }
}
```

The following exception is logged:

```
PS C:\File\Path\Example> dotnet run
Unhandled exception. OpenQA.Selenium.WebDriverException: Content-Type header is missing
   at OpenQA.Selenium.Remote.RemoteWebDriver.UnpackAndThrowOnError(Response errorResponse)
   at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.Remote.RemoteWebDriver.StartSession(ICapabilities desiredCapabilities)
   at OpenQA.Selenium.Remote.RemoteWebDriver..ctor(ICommandExecutor commandExecutor, ICapabilities desiredCapabilities)
   at OpenQA.Selenium.Remote.RemoteWebDriver..ctor(Uri remoteAddress, ICapabilities desiredCapabilities, TimeSpan commandTimeout)
   at OpenQA.Selenium.Remote.RemoteWebDriver..ctor(Uri remoteAddress, ICapabilities desiredCapab
```

## Expected behavior

The exception should not be thrown and the driver should be useable.

## Environment
Again not sure what to put here. My laptop is a windows laptop but the grid is running inside a linux container.

**Comment by connelhooley** [comment]
I also get the same error when using Firefox:

```c#
using System;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;

namespace Example
{
    class Program
    {
        static void Main()
        {
            new RemoteWebDriver(new Uri("http://localhost:4444"), new FirefoxOptions());
            Console.WriteLine("Done!");
        }
    }
}

```

**Comment by connelhooley** [comment]
This is the output of the docker containers, nothing that looks like an error:

```
PS C:\File\Path\Example> docker-compose --file "docker-compose.selenium.yml" up
Creating network "example_default" with the default driver
Creating selenium-hub ... done
Creating example_opera_1   ... done
Creating example_firefox_1 ... done
Creating example_chrome_1  ... done
Attaching to selenium-hub, example_firefox_1, example_chrome_1, example_opera_1
selenium-hub    | 2020-08-30 19:36:46,185 INFO Included extra file "/etc/supervisor/conf.d/selenium-grid-hub.conf" during parsing
selenium-hub    | 2020-08-30 19:36:46,187 INFO supervisord started with pid 7
firefox_1       | 2020-08-30 19:36:46,906 INFO Included extra file "/etc/supervisor/conf.d/selenium.conf" during parsing
firefox_1       | 2020-08-30 19:36:46,915 INFO supervisord started with pid 7
chrome_1        | 2020-08-30 19:36:47,028 INFO Included extra file "/etc/supervisor/conf.d/selenium.conf" during parsing
chrome_1        | 2020-08-30 19:36:47,030 INFO supervisord started with pid 7
opera_1         | 2020-08-30 19:36:47,036 INFO Included extra file "/etc/supervisor/conf.d/selenium.conf" during parsing
opera_1         | 2020-08-30 19:36:47,037 INFO supervisord started with pid 7
selenium-hub    | 2020-08-30 19:36:47,192 INFO spawned: 'selenium-grid-hub' with pid 10
selenium-hub    | Starting Selenium Grid Hub...
selenium-hub    | 2020-08-30 19:36:47,207 INFO success: selenium-grid-hub entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
selenium-hub    | 19:36:47.454 INFO [LoggingOptions.getTracer] - Using OpenTelemetry for tracing   
selenium-hub    | 19:36:47.455 INFO [LoggingOptions.createTracer] - Using OpenTelemetry for tracing
selenium-hub    | 19:36:47.516 INFO [BoundZmqEventBus.<init>] - XPUB binding to [binding to tcp://*:4442, advertising as tcp://192.168.160.2:4442], XSUB binding to [binding to tcp://*:4443, advertising as 
tcp://192.168.160.2:4443]
selenium-hub    | 19:36:47.550 INFO [UnboundZmqEventBus.<init>] - Connecting to tcp://192.168.160.2:4442 and tcp://192.168.160.2:4443
selenium-hub    | 19:36:47.565 INFO [UnboundZmqEventBus.<init>] - Sockets created
selenium-hub    | 19:36:47.580 INFO [UnboundZmqEventBus.lambda$new$6] - Bus started
selenium-hub    | 19:36:47.781 INFO [BoundZmqEventBus.<init>] - Event bus ready
firefox_1       | 2020-08-30 19:36:47,916 INFO spawned: 'xvfb' with pid 10
firefox_1       | 2020-08-30 19:36:47,917 INFO spawned: 'fluxbox' with pid 11      
firefox_1       | 2020-08-30 19:36:47,918 INFO spawned: 'vnc' with pid 12
firefox_1       | 2020-08-30 19:36:47,920 INFO spawned: 'selenium-node' with pid 13
firefox_1       | 2020-08-30 19:36:48,022 INFO success: xvfb entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
firefox_1       | 2020-08-30 19:36:48,022 INFO success: fluxbox entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)      
firefox_1       | 2020-08-30 19:36:48,022 INFO success: vnc entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
firefox_1       | 2020-08-30 19:36:48,022 INFO success: selenium-node entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
chrome_1        | 2020-08-30 19:36:48,031 INFO spawned: 'xvfb' with pid 10
chrome_1        | 2020-08-30 19:36:48,032 INFO spawned: 'fluxbox' with pid 11      
chrome_1        | 2020-08-30 19:36:48,034 INFO spawned: 'vnc' with pid 12
chrome_1        | 2020-08-30 19:36:48,035 INFO spawned: 'selenium-node' with pid 13
opera_1         | 2020-08-30 19:36:48,039 INFO spawned: 'xvfb' with pid 10
opera_1         | 2020-08-30 19:36:48,041 INFO spawned: 'fluxbox' with pid 11      
opera_1         | 2020-08-30 19:36:48,042 INFO spawned: 'vnc' with pid 12
opera_1         | 2020-08-30 19:36:48,044 INFO spawned: 'selenium-node' with pid 13
chrome_1        | 2020-08-30 19:36:48,263 INFO success: xvfb entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
chrome_1        | 2020-08-30 19:36:48,266 INFO success: fluxbox entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)      
chrome_1        | 2020-08-30 19:36:48,267 INFO success: vnc entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
chrome_1        | 2020-08-30 19:36:48,267 INFO success: selenium-node entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
opera_1         | 2020-08-30 19:36:48,287 INFO success: xvfb entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
opera_1         | 2020-08-30 19:36:48,287 INFO success: fluxbox entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)      
opera_1         | 2020-08-30 19:36:48,287 INFO success: vnc entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
opera_1         | 2020-08-30 19:36:48,287 INFO success: selenium-node entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
selenium-hub    | 19:36:48.627 INFO [Hub.execute] - Started Selenium hub 4.0.0-alpha-7 (revision Unknown): http://192.168.160.2:4444
firefox_1       | 19:36:49.201 INFO [LoggingOptions.getTracer] - Using OpenTelemetry for tracing   
firefox_1       | 19:36:49.205 INFO [LoggingOptions.createTracer] - Using OpenTelemetry for tracing
opera_1         | 19:36:49.354 INFO [LoggingOptions.getTracer] - Using OpenTelemetry for tracing   
opera_1         | 19:36:49.355 INFO [LoggingOptions.createTracer] - Using OpenTelemetry for tracing
firefox_1       | 19:36:49.374 INFO [UnboundZmqEventBus.<init>] - Connecting to tcp://selenium-hub:4442 and tcp://selenium-hub:4443
chrome_1        | 19:36:49.417 INFO [LoggingOptions.getTracer] - Using OpenTelemetry for tracing   
chrome_1        | 19:36:49.422 INFO [LoggingOptions.createTracer] - Using OpenTelemetry for tracing
opera_1         | 19:36:49.485 INFO [UnboundZmqEventBus.<init>] - Connecting to tcp://selenium-hub:4442 and tcp://selenium-hub:4443
firefox_1       | 19:36:49.499 INFO [UnboundZmqEventBus.<init>] - Sockets created
firefox_1       | 19:36:49.527 INFO [UnboundZmqEventBus.lambda$new$6] - Bus started
chrome_1        | 19:36:49.573 INFO [UnboundZmqEventBus.<init>] - Connecting to tcp://selenium-hub:4442 and tcp://selenium-hub:4443
opera_1         | 19:36:49.653 INFO [UnboundZmqEventBus.<init>] - Sockets created
opera_1         | 19:36:49.680 INFO [UnboundZmqEventBus.lambda$new$6] - Bus started
chrome_1        | 19:36:49.712 INFO [UnboundZmqEventBus.<init>] - Sockets created
chrome_1        | 19:36:49.728 INFO [UnboundZmqEventBus.lambda$new$6] - Bus started
firefox_1       | 19:36:49.753 INFO [NodeServer.execute] - Reporting self as: http://192.168.160.3:5555
firefox_1       | 19:36:49.759 INFO [LoggingOptions.getTracer] - Using OpenTelemetry for tracing       
firefox_1       | 19:36:49.762 INFO [UnboundZmqEventBus.<init>] - Connecting to tcp://selenium-hub:4442 and tcp://selenium-hub:4443
firefox_1       | 19:36:49.768 INFO [UnboundZmqEventBus.<init>] - Sockets created
firefox_1       | 19:36:49.789 INFO [UnboundZmqEventBus.lambda$new$6] - Bus started
opera_1         | 19:36:49.914 INFO [NodeServer.execute] - Reporting self as: http://192.168.160.4:5555
opera_1         | 19:36:49.918 INFO [LoggingOptions.getTracer] - Using OpenTelemetry for tracing
opera_1         | 19:36:49.919 INFO [UnboundZmqEventBus.<init>] - Connecting to tcp://selenium-hub:4442 and tcp://selenium-hub:4443
opera_1         | 19:36:49.922 INFO [UnboundZmqEventBus.<init>] - Sockets created
opera_1         | 19:36:49.928 INFO [UnboundZmqEventBus.lambda$new$6] - Bus started
chrome_1        | 19:36:49.940 INFO [NodeServer.execute] - Reporting self as: http://192.168.160.5:5555
chrome_1        | 19:36:49.943 INFO [LoggingOptions.getTracer] - Using OpenTelemetry for tracing
chrome_1        | 19:36:49.947 INFO [UnboundZmqEventBus.<init>] - Connecting to tcp://selenium-hub:4442 and tcp://selenium-hub:4443
chrome_1        | 19:36:49.949 INFO [UnboundZmqEventBus.<init>] - Sockets created
chrome_1        | 19:36:49.953 INFO [UnboundZmqEventBus.lambda$new$6] - Bus started
firefox_1       | 19:36:50.050 INFO [NodeOptions.report] - Adding Firefox for {"browserName": "firefox"} 2 times
firefox_1       | 19:36:50.198 INFO [NodeServer.execute] - Started Selenium node 4.0.0-alpha-7 (revision Unknown): http://192.168.160.3:5555
firefox_1       | 19:36:50.199 INFO [NodeServer.execute] - Starting registration process for node id 0f27d3ed-2303-45ba-985e-dc65d052ef77   
opera_1         | 19:36:50.222 INFO [NodeOptions.report] - Adding Opera for {"browserName": "operablink"} 2 times
chrome_1        | 19:36:50.332 INFO [NodeOptions.report] - Adding Chrome for {"browserName": "chrome"} 2 times
selenium-hub    | 19:36:50.328 INFO [LocalDistributor.refresh] - Creating a new remote node for http://192.168.160.3:5555
opera_1         | 19:36:50.466 INFO [NodeServer.execute] - Started Selenium node 4.0.0-alpha-7 (revision Unknown): http://192.168.160.4:5555
opera_1         | 19:36:50.467 INFO [NodeServer.execute] - Starting registration process for node id c29fc6cf-6ee5-46a2-b893-61070d56ec4b   
chrome_1        | 19:36:50.612 INFO [NodeServer.execute] - Started Selenium node 4.0.0-alpha-7 (revision Unknown): http://192.168.160.5:5555
chrome_1        | 19:36:50.613 INFO [NodeServer.execute] - Starting registration process for node id d78d107a-dab6-4737-b7b0-54713d8423f5   
firefox_1       | 19:36:50.927 INFO [LoggingOptions$1.lambda$export$1] - {"traceId": "e135cffdd97f6620f07e1935881b2dca","spanId": "746135a19579bc12","spanKind": "INTERNAL","eventTime": 1598816210923439601,"eventName": "HTTP request execution complete","attributes": {"http.status_code": 200,"http.handler_class": "org.openqa.selenium.remote.http.Route$TemplatizedRoute","http.url": "\u002fstatus","http.method": "GET"}}
firefox_1       |
selenium-hub    | 19:36:51.027 INFO [LoggingOptions$1.lambda$export$1] - {"traceId": "e135cffdd97f6620f07e1935881b2dca","spanId": "450ce0fc5f2596bb","spanKind": "INTERNAL","eventTime": 1598816211019662740,"eventName": "HTTP request received response","attributes": {"http.status_code": 200,"http.client_class": "org.openqa.selenium.remote.http.netty.NettyClient","http.url": "\u002fstatus","http.method": "GET"}}
selenium-hub    | 
selenium-hub    | 19:36:51.062 INFO [LocalDistributor.add] - Added node 0f27d3ed-2303-45ba-985e-dc65d052ef77.
firefox_1       | 19:36:51.071 INFO [LoggingOptions$1.lambda$export$1] - {"traceId": "49790ac00fcb41e24150d2fbe520e71b","spanId": "ef2d58d8cd5bf6ff","spanKind": "INTERNAL","eventTime": 1598816211069722700,"eventName": "HTTP request execution complete","attributes": {"http.status_code": 200,"http.handler_class": "org.openqa.selenium.remote.http.Route$TemplatizedRoute","http.url": "\u002fstatus","http.method": "GET"}}
firefox_1       |
selenium-hub    | 19:36:51.075 INFO [LoggingOptions$1.lambda$export$1] - {"traceId": "49790ac00fcb41e24150d2fbe520e71b","spanId": "f2bb03d02e490b8a","spanKind": "INTERNAL","eventTime": 1598816211074538402,"eventName": "HTTP request received response","attributes": {"http.status_code": 200,"http.client_class": "org.openqa.selenium.remote.http.netty.NettyClient","http.url": "\u002fstatus","http.method": "GET"}}
selenium-hub    |
selenium-hub    | 19:36:51.076 INFO [Host.lambda$new$0] - Changing status of node 0f27d3ed-2303-45ba-985e-dc65d052ef77 from DOWN to UP. Reason: http://192.168.160.3:5555 is ok
selenium-hub    | 19:36:51.081 INFO [LocalDistributor.refresh] - Creating a new remote node for http://192.168.160.4:5555
firefox_1       | 19:36:51.087 INFO [NodeServer.lambda$execute$1] - Node has been added
firefox_1       | 19:36:51.103 INFO [LoggingOptions$1.lambda$export$1] - {"traceId": "afa0244dffbc0fe9c7ea69b12b605cb3","spanId": "c40324ecd17d5556","spanKind": "INTERNAL","eventTime": 1598816211101984700,"eventName": "HTTP request execution complete","attributes": {"http.status_code": 200,"http.handler_class": "org.openqa.selenium.remote.http.Route$TemplatizedRoute","http.url": "\u002fstatus","http.method": "GET"}}
firefox_1       |
selenium-hub    | 19:36:51.120 INFO [LoggingOptions$1.lambda$export$1] - {"traceId": "afa0244dffbc0fe9c7ea69b12b605cb3","spanId": "ad3604cf70ee5069","spanKind": "INTERNAL","eventTime": 1598816211114806302,"eventName": "HTTP request received response","attributes": {"http.status_code": 200,"http.client_class": "org.openqa.selenium.remote.http.netty.NettyClient","http.url": "\u002fstatus","http.method": "GET"}}
selenium-hub    |
opera_1         | 19:36:51.208 INFO [LoggingOptions$1.lambda$export$1] - {"traceId": "a8f5496ea2cdc1b9b5031e5cb85aef73","spanId": "55d4673cd9a7cfc1","spanKind": "INTERNAL","eventTime": 1598816211203537703,"eventName": "HTTP request execution complete","attributes": {"http.status_code": 200,"http.handler_class": "org.openqa.selenium.remote.http.Route$TemplatizedRoute","http.url": "\u002fstatus","http.method": "GET"}}
opera_1         |
selenium-hub    | 19:36:51.240 INFO [LoggingOptions$1.lambda$export$1] - {"traceId": "a8f5496ea2cdc1b9b5031e5cb85aef73","spanId": "78632854af502cbf","spanKind": "INTERNAL","eventTime": 1598816211239560923,"eventName": "HTTP request received response","attributes": {"http.status_code": 200,"http.client_class": "org.openqa.selenium.remote.http.netty.NettyClient","http.url": "\u002fstatus","http.method": "GET"}}
selenium-hub    |
selenium-hub    | 19:36:51.242 INFO [LocalDistributor.add] - Added node c29fc6cf-6ee5-46a2-b893-61070d56ec4b.
opera_1         | 19:36:51.247 INFO [LoggingOptions$1.lambda$export$1] - {"traceId": "719ce86697aa923db3e5825a97821316","spanId": "bda71ea462d7c6c1","spanKind": "INTERNAL","eventTime": 1598816211245667200,"eventName": "HTTP request execution complete","attributes": {"http.status_code": 200,"http.handler_class": "org.openqa.selenium.remote.http.Route$TemplatizedRoute","http.url": "\u002fstatus","http.method": "GET"}}
opera_1         |
selenium-hub    | 19:36:51.250 INFO [LoggingOptions$1.lambda$export$1] - {"traceId": "719ce86697aa923db3e5825a97821316","spanId": "e5df6b51c94aff0d","spanKind": "INTERNAL","eventTime": 1598816211249103001,"eventName": "HTTP request received response","attributes": {"http.status_code": 200,"http.client_class": "org.openqa.selenium.remote.http.netty.NettyClient","http.url": "\u002fstatus","http.method": "GET"}}
selenium-hub    |
selenium-hub    | 19:36:51.250 INFO [Host.lambda$new$0] - Changing status of node c29fc6cf-6ee5-46a2-b893-61070d56ec4b from DOWN to UP. Reason: http://192.168.160.4:5555 is ok
selenium-hub    | 19:36:51.252 INFO [LocalDistributor.refresh] - Creating a new remote node for http://192.168.160.5:5555
opera_1         | 19:36:51.257 INFO [NodeServer.lambda$execute$1] - Node has been added
opera_1         | 19:36:51.261 INFO [LoggingOptions$1.lambda$export$1] - {"traceId": "cec52037e8816660749f2ad5637a04ee","spanId": "2614b9de36c93327","spanKind": "INTERNAL","eventTime": 1598816211260385900,"eventName": "HTTP request execution complete","attributes": {"http.status_code": 200,"http.handler_class": "org.openqa.selenium.remote.http.Route$TemplatizedRoute","http.url": "\u002fstatus","http.method": "GET"}}
opera_1         |
selenium-hub    | 19:36:51.265 INFO [LoggingOptions$1.lambda$export$1] - {"traceId": "cec52037e8816660749f2ad5637a04ee","spanId": "a6838b64e168f387","spanKind": "INTERNAL","eventTime": 1598816211264205101,"eventName": "HTTP request received response","attributes": {"http.status_code": 200,"http.client_class": "org.openqa.selenium.remote.http.netty.NettyClient","http.url": "\u002fstatus","http.method": "GET"}}
selenium-hub    |
chrome_1        | 19:36:51.364 INFO [LoggingOptions$1.lambda$export$1] - {"traceId": "d01f80792f7995fe2c26a292c3d8001a","spanId": "c8eb3168fe5a622a","spanKind": "INTERNAL","eventTime": 1598816211360583203,"eventName": "HTTP request execution complete","attributes": {"http.status_code": 200,"http.handler_class": "org.openqa.selenium.remote.http.Route$TemplatizedRoute","http.url": "\u002fstatus","http.method": "GET"}}
chrome_1        |
selenium-hub    | 19:36:51.389 INFO [LoggingOptions$1.lambda$export$1] - {"traceId": "d01f80792f7995fe2c26a292c3d8001a","spanId": "d07d9e44b5b4ef4c","spanKind": "INTERNAL","eventTime": 1598816211388568322,"eventName": "HTTP request received response","attributes": {"http.status_code": 200,"http.client_class": "org.openqa.selenium.remote.http.netty.NettyClient","http.url": "\u002fstatus","http.method": "GET"}}
selenium-hub    |
selenium-hub    | 19:36:51.391 INFO [LocalDistributor.add] - Added node d78d107a-dab6-4737-b7b0-54713d8423f5.
chrome_1        | 19:36:51.401 INFO [LoggingOptions$1.lambda$export$1] - {"traceId": "5e10c324452c04be3915aa14413fa15b","spanId": "f2f63cd19f8a6c8b","spanKind": "INTERNAL","eventTime": 1598816211400443600,"eventName": "HTTP request execution complete","attributes": {"http.status_code": 200,"http.handler_class": "org.openqa.selenium.remote.http.Route$TemplatizedRoute","http.url": "\u002fstatus","http.method": "GET"}}
chrome_1        |
selenium-hub    | 19:36:51.404 INFO [LoggingOptions$1.lambda$export$1] - {"traceId": "5e10c324452c04be3915aa14413fa15b","spanId": "7b2973f520b3ff45","spanKind": "INTERNAL","eventTime": 1598816211403564402,"eventName": "HTTP request received response","attributes": {"http.status_code": 200,"http.client_class": "org.openqa.selenium.remote.http.netty.NettyClient","http.url": "\u002fstatus","http.method": "GET"}}
selenium-hub    |
selenium-hub    | 19:36:51.405 INFO [Host.lambda$new$0] - Changing status of node d78d107a-dab6-4737-b7b0-54713d8423f5 from DOWN to UP. Reason: http://192.168.160.5:5555 is ok
chrome_1        | 19:36:51.412 INFO [NodeServer.lambda$execute$1] - Node has been added
chrome_1        | 19:36:51.422 INFO [LoggingOptions$1.lambda$export$1] - {"traceId": "40c7fd9f9b8c317daa8d40e03e6b6fbe","spanId": "a5dfa08464e08b77","spanKind": "INTERNAL","eventTime": 1598816211420306400,"eventName": "HTTP request execution complete","attributes": {"http.status_code": 200,"http.handler_class": "org.openqa.selenium.remote.http.Route$TemplatizedRoute","http.url": "\u002fstatus","http.method": "GET"}}
chrome_1        |
selenium-hub    | 19:36:51.428 INFO [LoggingOptions$1.lambda$export$1] - {"traceId": "40c7fd9f9b8c317daa8d40e03e6b6fbe","spanId": "5fdcb48d158f708b","spanKind": "INTERNAL","eventTime": 1598816211426440904,"eventName": "HTTP request received response","attributes": {"http.status_code": 200,"http.client_class": "org.openqa.selenium.remote.http.netty.NettyClient","http.url": "\u002fstatus","http.method": "GET"}}
selenium-hub    |
```

**Comment by abhi-selenium** [comment]
I'm also getting the same issue.

**Comment by ivanbenko** [comment]
I'm getting the same issue on calling `webElement.getText()`. It's started happen on the image `selenium/standalone-chrome:4.0` and did work well on `selenium/standalone-chrome:4.0.0-alpha-6-20200730`

**Comment by michalkrupiarz** [comment]
Exacly same issue with:
driver.manage().deleteAllCookies();
and
waitDriver.until(ExpectedConditions.elementToBeClickable(by));

Tests are written in java and version: node-firefox:4.0.0-alpha-7-prerelease-20200826

**Comment by jojjeninja** [comment]
Same here, I'm also getting the same issue.

**Comment by phirina** [comment]
Please, try to use this version: https://github.com/SeleniumHQ/docker-selenium/tree/selenium-3

**Comment by michalkrupiarz** [comment]
> Please, try to use this version: https://github.com/SeleniumHQ/docker-selenium/tree/selenium-3

Why we should use this version? Correct me if i`m wrong but 4.0 and 3, are completly different.

**Comment by diemol** [comment]
@michalkrupiarz correct, this issue is about Grid 4.

We will look at this soon, thank you for reporting it.

**Comment by diemol** [comment]
Just FYI, I was able to reproduce it, we will have a deeper look.

**Comment by diemol** [comment]
Pushed a fix, prerelease docker images will be published soon

**Comment by diemol** [comment]
https://github.com/SeleniumHQ/docker-selenium/releases/tag/4.0.0-alpha-7-prerelease-20200904

**Comment by amykhaylyshyn** [comment]
I'm still getting this issue on 85.0-chromedriver-85.0-20200905.

Sample code:
```import { Builder } from 'selenium-webdriver';
import Chrome from 'selenium-webdriver/chrome';

async function main() {
    const wd = new Builder().forBrowser('chrome').usingServer('http://localhost:4444/wd/hub')
        .setChromeOptions(
            new Chrome.Options()
                .headless())
        .build();
    wd.get('https://example.com');
    const title = await wd.getTitle();
    console.log(`title: ${title}`);
}

main().catch(err => {
    console.error(err);
    process.exit(1);
});
```

**Comment by moreorover** [comment]
Would like to take a second to report that also having this issue on 85.0-20200905 using Java.

```
    @Bean
    public ScraperFetchingHtmlSeleniumState scraperFetchingHtmlSeleniumState() {
        URL remoteAddress = null;
        try {
            remoteAddress = new URL(remoteBrowserUrl);
        } catch (MalformedURLException e) {
            log.info(e.getMessage());
        }
        ChromeOptions chromeOptions = new ChromeOptions();
        chromeOptions.setHeadless(true);

        WebDriver webDriver = new RemoteWebDriver(remoteAddress, chromeOptions);

        return new ScraperFetchingHtmlSeleniumState(webDriver);
    }
```

**Comment by diemol** [comment]
I guess you are using the standalone images?
If so, I just noticed we missed to add a configuration flag there. 
I will add it and a prerelease will happen in the next minutes.

**Comment by moreorover** [comment]
Yes, using standalone.

**Comment by moreorover** [comment]
Bumped container version to selenium/standalone-chrome:4.0.0-alpha-7-prerelease-20200907 and the issue seems to be resolved. However, I found that I get Content-Type header is missing only when I'm trying to quit the webDriver right after I obtain the page source.

```
                this.webDriver.get(scraper.getCurrentPageUrl());
                String source = this.webDriver.getPageSource();
                this.webDriver.quit();
                Document d = Jsoup.parse(source);
                scraper.setPageHtmlDocument(d);
```

If lets say I remove this.webDriver.quit(); I do not get Content-Type error.

**Comment by amykhaylyshyn** [comment]
@diemol Thank you, now it works!
PS. Yes, it was chrome-standalone image

**Comment by victorBychinski** [comment]
Hello @diemol ,
The Problem was reproduced on Grid env with  selenium/hub:4.0.0-alpha-7-20201119 +selenium/node-chrome:4.0.0-alpha-7-20201119
nuget packages:
Selenium.Support 4.0.0-alpha07
dotnet add package Selenium.Selenium.WebDriver 4.0.0-alpha07

**Comment by jimevans** [comment]
@victorBychinski The .NET bindings had a legitimate issue that was fixed in 62bb990

**Comment by victorBychinski** [comment]
Hello @jimevans 
according to Travis CI log a build with the commit failed. Does it mean the change is not in the latest alpha?  I`m asking because I have the latest version of the nuget packages and alpha-7-20201119  is the latest version on docker containers from docker hub.
Thanks.

**Comment by diemol** [comment]
@victorBychinski the issue is fixed in `trunk` for the .NET bindings. However, this does not mean it was released. This fix will be part of the next release.

On the other hand, if you are using the `alpha-7-20201119` docker images, you should not be bumping into this issue because (for now) they are started with a flag that ignores the check.

If you have more questions, please drop by our Slack/IRC channel, the links to join are available at https://www.selenium.dev/support/

**Comment by undron** [comment]
@diemol The issue still exists for `Quit()` method. Checked for the last code in trunk and `selenium-server-4.0.0-prerelease-beta-1-02d5e641d5.jar`. 
Request 
```
{Method: DELETE, RequestUri: 'http://127.0.0.1:4444/session/a736299e4bce57cddae66b151ad0396f', Version: 1.1, Content: <null>, Headers:
{
  User-Agent: selenium/4.0.0
  User-Agent: (.net windows)
  Accept: application/json
  Accept: image/png
}}
```
gives the response from server:
```
{
  "value": {
    "error": "unknown error",
    "message": "Content-Type header is missing",
    "stacktrace": ""
  }
}
```

**Comment by diemol** [comment]
@undron, are you starting the Grid with the flag `-relax-checks true`?
If so, and the error is there, please open a new issue.

**Comment by undron** [comment]
@diemol Thanks, it's working with `--relax-checks true`!
