### ISSUE TITLE
Node not attaching to hub due to "delay must be less than the maxDuration" error 4.0.0-beta-1-20210215

### ISSUE THREAD

**Issue by ambirag** [SeleniumHQ/selenium#9226]
## 🐛 Bug Report

version: 4.0.0-beta-1-20210215
When deploy grid in k8s, nodes are not registering with grid.
Reason:
`kubectl logs test-selenium-chrome-54777b787-f94mf 
2021-03-01 16:14:07,017 INFO Included extra file "/etc/supervisor/conf.d/selenium.conf" during parsing
2021-03-01 16:14:07,099 INFO supervisord started with pid 7
2021-03-01 16:14:08,101 INFO spawned: 'xvfb' with pid 9
2021-03-01 16:14:08,102 INFO spawned: 'vnc' with pid 10
2021-03-01 16:14:08,103 INFO spawned: 'selenium-node' with pid 11
2021-03-01 16:14:08,106 INFO success: xvfb entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
2021-03-01 16:14:08,106 INFO success: vnc entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
2021-03-01 16:14:08,106 INFO success: selenium-node entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
Configuring server...
Setting up SE_NODE_HOST...
Setting up SE_NODE_PORT...
Starting Selenium Grid Node with configuration: 
[events]
publish = "tcp://test-selenium-hub:4442"
subscribe = "tcp://test-selenium-hub:4443"

[node]
max-concurrent-sessions = 1

Picked up JAVA_TOOL_OPTIONS: -Xmx700m
16:14:11.505 INFO [LogManager$RootLogger.log] - Using the system default encoding
16:14:11.700 INFO [OpenTelemetryTracer.createTracer] - Using OpenTelemetry for tracing
16:14:12.305 INFO [UnboundZmqEventBus.<init>] - Connecting to tcp://test-selenium-hub:4442 and tcp://test-selenium-hub:4443
16:14:12.608 INFO [UnboundZmqEventBus.<init>] - Sockets created
16:14:12.709 INFO [UnboundZmqEventBus.<init>] - Event bus ready
16:14:13.199 INFO [NodeServer.createHandlers] - Reporting self as: http://10.5.90.151:5555
16:14:13.409 INFO [NodeOptions.report] - Adding Chrome for {"browserName": "chrome"} 1 times
16:14:13.500 INFO [Node.<init>] - Binding additional locator mechanisms: name, id
Exception in thread "main" java.lang.IllegalStateException: delay must be less than the maxDuration
	at net.jodah.failsafe.internal.util.Assert.state(Assert.java:38)
	at net.jodah.failsafe.RetryPolicy.withDelay(RetryPolicy.java:415)
	at org.openqa.selenium.grid.node.httpd.NodeServer$1.start(NodeServer.java:193)
	at org.openqa.selenium.grid.node.httpd.NodeServer$1.start(NodeServer.java:183)
	at org.openqa.selenium.grid.node.httpd.NodeServer.execute(NodeServer.java:224)
	at org.openqa.selenium.grid.TemplateGridCommand.lambda$configure$2(TemplateGridCommand.java:101)
	at org.openqa.selenium.grid.Main.launch(Main.java:154)
	at org.openqa.selenium.grid.Main.go(Main.java:88)
	at org.openqa.selenium.grid.Main.main(Main.java:54)
`

## To Reproduce

I found the cause, which is part of this commit
a) https://github.com/SeleniumHQ/selenium/commit/8500500c82f088e64afc7496e706b4c590e994f0#diff-5e7836f90bf50768ae656f9ddcfec06a3c33e83f277dd0662b67770edcc06f29

Cause: The name of "--register-period" should be "register-period" and not "register-cycle"

b) https://github.com/SeleniumHQ/selenium/blob/selenium-4.0.0-beta-1/java/server/src/org/openqa/selenium/grid/node/config/NodeOptions.java#L89

Here you can see, getRegisterPeriod() calls with name "register-period", but because there is no "register-period" in a), it defaults to 1, but getRegisterCycle gets 10, hence the above error. "delay must be less than the maxDuration"

## Environment

OS: LINUX
Language Bindings version: Java
Selenium Grid version (if applicable): 4.0.0-beta-1-20210215

**Comment by diemol** [comment]
Good catch, thank you for reporting this, @ambirag!

**Comment by diemol** [comment]
Fixed by the referenced commit, will be available in "beta-2".

**Comment by ambirag** [comment]
This issue is still happening with 4.0.0-beta-3-prerelease-20210329 (tried with 4.0.0-beta-2-20210319 as well)
 
`
subscribe = "tcp://utap-selenium-hub:4443"

[node]
session-timeout = "300"
max-sessions = 1

Picked up JAVA_TOOL_OPTIONS: -Xmx700m
14:54:08.417 INFO [LogManager$RootLogger.log] - Using the system default encoding
14:54:08.503 INFO [OpenTelemetryTracer.createTracer] - Using OpenTelemetry for tracing
14:54:09.009 INFO [UnboundZmqEventBus.<init>] - Connecting to tcp://utap-selenium-hub:4442 and tcp://utap-selenium-hub:4443
14:54:09.504 INFO [UnboundZmqEventBus.<init>] - Sockets created
14:54:09.605 INFO [UnboundZmqEventBus.<init>] - Event bus ready
14:54:10.008 INFO [NodeServer.createHandlers] - Reporting self as: http://10.5.27.88:5555
14:54:10.207 INFO [NodeOptions.discoverDrivers] - Discovered 1 driver(s)
14:54:10.313 INFO [NodeOptions.report] - Adding Chrome for {"browserName": "chrome","platformName": "LINUX"} 1 times
14:54:10.407 INFO [Node.<init>] - Binding additional locator mechanisms: id, name
java.lang.reflect.InvocationTargetException
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.openqa.selenium.grid.Bootstrap.runMain(Bootstrap.java:77)
at org.openqa.selenium.grid.Bootstrap.main(Bootstrap.java:70)
Caused by: java.lang.IllegalStateException: delay must be less than the maxDuration
at net.jodah.failsafe.internal.util.Assert.state(Assert.java:38)
at net.jodah.failsafe.RetryPolicy.withDelay(RetryPolicy.java:415)
at org.openqa.selenium.grid.node.httpd.NodeServer$1.start(NodeServer.java:195)
at org.openqa.selenium.grid.node.httpd.NodeServer$1.start(NodeServer.java:185)
at org.openqa.selenium.grid.node.httpd.NodeServer.execute(NodeServer.java:226)
at org.openqa.selenium.grid.TemplateGridCommand.lambda$configure$4(TemplateGridCommand.java:129)
at org.openqa.selenium.grid.Main.launch(Main.java:83)
at org.openqa.selenium.grid.Main.go(Main.java:57)
at org.openqa.selenium.grid.Main.main(Main.java:42)
... 6 more
2021-04-01 14:54:11,626 INFO exited: selenium-node (exit status 1; not expected)
`
Error being **"delay must be less than the maxDuration"**, from here https://github.com/jhalterman/failsafe/blob/master/src/main/java/net/jodah/failsafe/RetryPolicy.java#L416, looks like 
nodeOptions.getRegisterPeriod() is the one causing this issue.
`
    RetryPolicy<Object> registrationPolicy = new RetryPolicy<>()
          .withMaxAttempts(-1)
          .withMaxDuration(nodeOptions.getRegisterPeriod())
          .withDelay(nodeOptions.getRegisterCycle())
          .handleResultIf(result -> true);
`
https://github.com/SeleniumHQ/selenium/blob/selenium-4.0.0-beta-2/java/server/src/org/openqa/selenium/grid/node/httpd/NodeServer.java#L194
@diemol  do you want me to open a new issue

**Comment by diemol** [comment]
Yes please, we need to see the complete configuration to reproduce it.

**Comment by ambirag** [comment]
created this https://github.com/SeleniumHQ/selenium/issues/9378
