### ISSUE TITLE
GRAPHQ

### ISSUE THREAD

**Issue by rotemironsrc** [SeleniumHQ/selenium#9421]
## 🐛 Bug Report

```
curl -X POST -H "Content-Type: application/json" --data '{"query":"{ session (id: "<session-id>") { id, capabilities, startTime, uri, nodeId, nodeUri, sessionDurationMillis, slot { id, stereotype, lastStarted } } } "}' -s <LINK_TO_GRAPHQL_ENDPOINT>
```

keep getting this error: “message”: “Exception while fetching data (/session) : No ongoing session found with the requested session id.“,

for sure this session id exist cause i see the id when i query the grid and i did the request the second i got the session_id from the web driver(chrome)
  

## To Reproduce

build web driver connection 
get the session id by code or do 

```
curl --location --request POST 'LINK_TO_GRAPHQL_ENDPOINT' \
--header 'Content-Type: application/json' \
--data-raw '{"query":"query sessionsInfo {\n    sessionsInfo {\n        sessionQueueRequests \n        sessions{\n            id\n            capabilities\n            startTime\n            uri\n            nodeId\n            nodeUri\n            sessionDurationMillis\n            slot {\n                id\n                stereotype\n                lastStarted\n            }\n        }\n    }\n}","variables":{}}'
```

replace <session-id>  with the session id:
curl -X POST -H "Content-Type: application/json" --data '{"query":"{ session (id: "<session-id>") { id, capabilities, startTime, uri, nodeId, nodeUri, sessionDurationMillis, slot { id, stereotype, lastStarted } } } "}' -s <LINK_TO_GRAPHQL_ENDPOINT>
 
## Expected behavior

```
{
    "errors": [
        {
            "message": "Exception while fetching data (/session) : No ongoing session found with the requested session id.",
            "locations": [
                {
                    "line": 2,
                    "column": 6
                }
            ],
            "path": [
                "session"
            ],
            "extensions": {
                "sessionId": "'8c86cb43abffe7c0cc5ef4ec4b6ed5fd'",
                "classification": "DataFetchingException"
            }
        }
    ],
    "data": null
}
```
 
## Environment

OS:  macOS
Browser: Chrome
Browser version: 89.0.4389.90
Browser Driver version: 89.0.4389.23 (61b08ee2c50024bab004e48d2b1b083cdbdac579-refs
Language Bindings version:  
Selenium Grid version (if applicable):  4.0.0-beta-3 (revision 909239cd9f)

**Comment by pujagani** [comment]
Thank you for providing the details. Appreciate it. I was able to reproduce the issue. It is fixed by https://github.com/SeleniumHQ/selenium/commit/38c2b3ff8b47968526625ff524b9d28cdd932526. The change is currently available in the trunk and it will be available in the next release.

**Comment by JohnA2** [comment]
It looks like this bug wasn't completely resolved. I'm trying to use the following query

curl -X POST -H "Content-Type: application/json" --data '{"query":"{ session (id: \"<session-id>\") { uri } } "}' -s http://localhost:4444/graphql

It works fine for the first session for Grid that I've just started (I use the hub+nodes). But  not for any subsequent sessions. I'm getting this error.

```
{
  "errors": [
    {
      "message": "Exception while fetching data (\u002fsession) : No ongoing session found with the requested session id.",
      "locations": [
        {
          "line": 1,
          "column": 3
        }
      ],
      "path": [
        "session"
      ],
      "extensions": {
        "sessionId": "77ed9225-eea9-4bb1-b9a4-1378bc3cbf17",
        "classification": "DataFetchingException"
      }
    }
  ],
  "data": null
}
```
The exception on the hub is
```
14:47:19.782 WARN [SimpleDataFetcherExceptionHandler.onException] - Exception while fetching data (/session) : No ongoing session found with the requested session id.
org.openqa.selenium.grid.graphql.SessionNotFoundException: No ongoing session found with the requested session id.
        at org.openqa.selenium.grid.graphql.SessionData.get(SessionData.java:65)
        at graphql.execution.ExecutionStrategy.fetchField(ExecutionStrategy.java:270)
        at graphql.execution.ExecutionStrategy.resolveFieldWithInfo(ExecutionStrategy.java:203)
        at graphql.execution.AsyncExecutionStrategy.execute(AsyncExecutionStrategy.java:60)
        at graphql.execution.Execution.executeOperation(Execution.java:165)
        at graphql.execution.Execution.execute(Execution.java:104)
        at graphql.GraphQL.execute(GraphQL.java:557)
        at graphql.GraphQL.parseValidateAndExecute(GraphQL.java:482)
        at graphql.GraphQL.executeAsync(GraphQL.java:446)
        at graphql.GraphQL.execute(GraphQL.java:377)
        at org.openqa.selenium.grid.graphql.GraphqlHandler.execute(GraphqlHandler.java:147)
        at org.openqa.selenium.remote.http.Route$TemplatizedRoute.handle(Route.java:192)
        at org.openqa.selenium.remote.http.Route.execute(Route.java:68)
        at org.openqa.selenium.remote.http.Route$CombinedRoute.handle(Route.java:336)
        at org.openqa.selenium.remote.http.Route.execute(Route.java:68)
        at org.openqa.selenium.remote.AddWebDriverSpecHeaders.lambda$apply$0(AddWebDriverSpecHeaders.java:35)
        at org.openqa.selenium.remote.ErrorFilter.lambda$apply$0(ErrorFilter.java:44)
        at org.openqa.selenium.remote.http.Filter$1.execute(Filter.java:64)
        at org.openqa.selenium.remote.ErrorFilter.lambda$apply$0(ErrorFilter.java:44)
        at org.openqa.selenium.remote.http.Filter$1.execute(Filter.java:64)
        at org.openqa.selenium.netty.server.SeleniumHandler.lambda$channelRead0$0(SeleniumHandler.java:44)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
```
I see that session id at http://localhost:4444/ui/index.html#/sessions , so it definitely exists.

**Comment by pujagani** [comment]
> Thank you for providing the details. Appreciate it. I was able to reproduce the issue. It is fixed by [38c2b3f](https://github.com/SeleniumHQ/selenium/commit/38c2b3ff8b47968526625ff524b9d28cdd932526). The change is currently available in the trunk and will be available in the next release.

Thank you for providing the details. Please provide the Selenium version used when the problem occurred on your end. The fix will be available in the next release as mentioned when closing the issue. I have re-confirmed on my local machine with the trunk that the issue is resolved. I have started one session and let it run for a few mins. I started a second session. When queried via GraphQL the session details are provided as excepted. Providing screenshots below that confirm the same.

<img width="1440" alt="Screenshot 2021-07-13 at 11 02 53 AM" src="https://user-images.githubusercontent.com/10705590/125396777-9d7c4c80-e3ca-11eb-9ead-a41ea7a84dff.png">

![Screenshot 2021-07-13 at 11 03 09 AM](https://user-images.githubusercontent.com/10705590/125396764-99502f00-e3ca-11eb-8a7b-49981b50985c.png)

Please provide the details in case I have missed something. I will be happy to look to at it from our end.

**Comment by JohnA2** [comment]
I tried it with selenium-4.0.0-beta-4. Did you make the commit after beta 4 was released? If yes, sorry, I thought it was between beta 3 and 4.

**Comment by diemol** [comment]
This change was done after `beta-4`. We have just done a pre-release and from this [link](https://github.com/SeleniumHQ/docker-selenium/releases/tag/4.0.0-rc-1-prerelease-20210713) you can grab a jar to try the change if you'd like.

**Comment by JohnA2** [comment]
I've tried the pre-release. It works fine with it. Thanks!
